/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `Cafe` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums";
import type * as Prisma from "../internal/prismaNamespace";

/**
 * Model Cafe
 *
 */
export type CafeModel =
  runtime.Types.Result.DefaultSelection<Prisma.$CafePayload>;

export type AggregateCafe = {
  _count: CafeCountAggregateOutputType | null;
  _avg: CafeAvgAggregateOutputType | null;
  _sum: CafeSumAggregateOutputType | null;
  _min: CafeMinAggregateOutputType | null;
  _max: CafeMaxAggregateOutputType | null;
};

export type CafeAvgAggregateOutputType = {
  id: number | null;
  latitude: runtime.Decimal | null;
  longitude: runtime.Decimal | null;
};

export type CafeSumAggregateOutputType = {
  id: bigint | null;
  latitude: runtime.Decimal | null;
  longitude: runtime.Decimal | null;
};

export type CafeMinAggregateOutputType = {
  id: bigint | null;
  slug: string | null;
  name: string | null;
  address: string | null;
  latitude: runtime.Decimal | null;
  longitude: runtime.Decimal | null;
  googleMapsUrl: string | null;
  instagramUrl: string | null;
  wifi: boolean | null;
  parking: string | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type CafeMaxAggregateOutputType = {
  id: bigint | null;
  slug: string | null;
  name: string | null;
  address: string | null;
  latitude: runtime.Decimal | null;
  longitude: runtime.Decimal | null;
  googleMapsUrl: string | null;
  instagramUrl: string | null;
  wifi: boolean | null;
  parking: string | null;
  createdAt: Date | null;
  updatedAt: Date | null;
};

export type CafeCountAggregateOutputType = {
  id: number;
  slug: number;
  name: number;
  address: number;
  latitude: number;
  longitude: number;
  googleMapsUrl: number;
  instagramUrl: number;
  wifi: number;
  parking: number;
  createdAt: number;
  updatedAt: number;
  _all: number;
};

export type CafeAvgAggregateInputType = {
  id?: true;
  latitude?: true;
  longitude?: true;
};

export type CafeSumAggregateInputType = {
  id?: true;
  latitude?: true;
  longitude?: true;
};

export type CafeMinAggregateInputType = {
  id?: true;
  slug?: true;
  name?: true;
  address?: true;
  latitude?: true;
  longitude?: true;
  googleMapsUrl?: true;
  instagramUrl?: true;
  wifi?: true;
  parking?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type CafeMaxAggregateInputType = {
  id?: true;
  slug?: true;
  name?: true;
  address?: true;
  latitude?: true;
  longitude?: true;
  googleMapsUrl?: true;
  instagramUrl?: true;
  wifi?: true;
  parking?: true;
  createdAt?: true;
  updatedAt?: true;
};

export type CafeCountAggregateInputType = {
  id?: true;
  slug?: true;
  name?: true;
  address?: true;
  latitude?: true;
  longitude?: true;
  googleMapsUrl?: true;
  instagramUrl?: true;
  wifi?: true;
  parking?: true;
  createdAt?: true;
  updatedAt?: true;
  _all?: true;
};

export type CafeAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Filter which Cafe to aggregate.
   */
  where?: Prisma.CafeWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Cafes to fetch.
   */
  orderBy?:
    | Prisma.CafeOrderByWithRelationInput
    | Prisma.CafeOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.CafeWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Cafes from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Cafes.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned Cafes
   **/
  _count?: true | CafeCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: CafeAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: CafeSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: CafeMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: CafeMaxAggregateInputType;
};

export type GetCafeAggregateType<T extends CafeAggregateArgs> = {
  [P in keyof T & keyof AggregateCafe]: P extends "_count" | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCafe[P]>
    : Prisma.GetScalarType<T[P], AggregateCafe[P]>;
};

export type CafeGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  where?: Prisma.CafeWhereInput;
  orderBy?:
    | Prisma.CafeOrderByWithAggregationInput
    | Prisma.CafeOrderByWithAggregationInput[];
  by: Prisma.CafeScalarFieldEnum[] | Prisma.CafeScalarFieldEnum;
  having?: Prisma.CafeScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: CafeCountAggregateInputType | true;
  _avg?: CafeAvgAggregateInputType;
  _sum?: CafeSumAggregateInputType;
  _min?: CafeMinAggregateInputType;
  _max?: CafeMaxAggregateInputType;
};

export type CafeGroupByOutputType = {
  id: bigint;
  slug: string;
  name: string;
  address: string;
  latitude: runtime.Decimal | null;
  longitude: runtime.Decimal | null;
  googleMapsUrl: string | null;
  instagramUrl: string | null;
  wifi: boolean;
  parking: string | null;
  createdAt: Date;
  updatedAt: Date;
  _count: CafeCountAggregateOutputType | null;
  _avg: CafeAvgAggregateOutputType | null;
  _sum: CafeSumAggregateOutputType | null;
  _min: CafeMinAggregateOutputType | null;
  _max: CafeMaxAggregateOutputType | null;
};

type GetCafeGroupByPayload<T extends CafeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CafeGroupByOutputType, T["by"]> & {
      [P in keyof T & keyof CafeGroupByOutputType]: P extends "_count"
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], CafeGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], CafeGroupByOutputType[P]>;
    }
  >
>;

export type CafeWhereInput = {
  AND?: Prisma.CafeWhereInput | Prisma.CafeWhereInput[];
  OR?: Prisma.CafeWhereInput[];
  NOT?: Prisma.CafeWhereInput | Prisma.CafeWhereInput[];
  id?: Prisma.BigIntFilter<"Cafe"> | bigint | number;
  slug?: Prisma.StringFilter<"Cafe"> | string;
  name?: Prisma.StringFilter<"Cafe"> | string;
  address?: Prisma.StringFilter<"Cafe"> | string;
  latitude?:
    | Prisma.DecimalNullableFilter<"Cafe">
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  longitude?:
    | Prisma.DecimalNullableFilter<"Cafe">
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  googleMapsUrl?: Prisma.StringNullableFilter<"Cafe"> | string | null;
  instagramUrl?: Prisma.StringNullableFilter<"Cafe"> | string | null;
  wifi?: Prisma.BoolFilter<"Cafe"> | boolean;
  parking?: Prisma.StringNullableFilter<"Cafe"> | string | null;
  createdAt?: Prisma.DateTimeFilter<"Cafe"> | Date | string;
  updatedAt?: Prisma.DateTimeFilter<"Cafe"> | Date | string;
  openingHours?: Prisma.OpeningHourListRelationFilter;
  paymentMethods?: Prisma.CafePaymentMethodListRelationFilter;
};

export type CafeOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  slug?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  address?: Prisma.SortOrder;
  latitude?: Prisma.SortOrderInput | Prisma.SortOrder;
  longitude?: Prisma.SortOrderInput | Prisma.SortOrder;
  googleMapsUrl?: Prisma.SortOrderInput | Prisma.SortOrder;
  instagramUrl?: Prisma.SortOrderInput | Prisma.SortOrder;
  wifi?: Prisma.SortOrder;
  parking?: Prisma.SortOrderInput | Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  openingHours?: Prisma.OpeningHourOrderByRelationAggregateInput;
  paymentMethods?: Prisma.CafePaymentMethodOrderByRelationAggregateInput;
  _relevance?: Prisma.CafeOrderByRelevanceInput;
};

export type CafeWhereUniqueInput = Prisma.AtLeast<
  {
    id?: bigint | number;
    slug?: string;
    AND?: Prisma.CafeWhereInput | Prisma.CafeWhereInput[];
    OR?: Prisma.CafeWhereInput[];
    NOT?: Prisma.CafeWhereInput | Prisma.CafeWhereInput[];
    name?: Prisma.StringFilter<"Cafe"> | string;
    address?: Prisma.StringFilter<"Cafe"> | string;
    latitude?:
      | Prisma.DecimalNullableFilter<"Cafe">
      | runtime.Decimal
      | runtime.DecimalJsLike
      | number
      | string
      | null;
    longitude?:
      | Prisma.DecimalNullableFilter<"Cafe">
      | runtime.Decimal
      | runtime.DecimalJsLike
      | number
      | string
      | null;
    googleMapsUrl?: Prisma.StringNullableFilter<"Cafe"> | string | null;
    instagramUrl?: Prisma.StringNullableFilter<"Cafe"> | string | null;
    wifi?: Prisma.BoolFilter<"Cafe"> | boolean;
    parking?: Prisma.StringNullableFilter<"Cafe"> | string | null;
    createdAt?: Prisma.DateTimeFilter<"Cafe"> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<"Cafe"> | Date | string;
    openingHours?: Prisma.OpeningHourListRelationFilter;
    paymentMethods?: Prisma.CafePaymentMethodListRelationFilter;
  },
  "id" | "slug"
>;

export type CafeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  slug?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  address?: Prisma.SortOrder;
  latitude?: Prisma.SortOrderInput | Prisma.SortOrder;
  longitude?: Prisma.SortOrderInput | Prisma.SortOrder;
  googleMapsUrl?: Prisma.SortOrderInput | Prisma.SortOrder;
  instagramUrl?: Prisma.SortOrderInput | Prisma.SortOrder;
  wifi?: Prisma.SortOrder;
  parking?: Prisma.SortOrderInput | Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
  _count?: Prisma.CafeCountOrderByAggregateInput;
  _avg?: Prisma.CafeAvgOrderByAggregateInput;
  _max?: Prisma.CafeMaxOrderByAggregateInput;
  _min?: Prisma.CafeMinOrderByAggregateInput;
  _sum?: Prisma.CafeSumOrderByAggregateInput;
};

export type CafeScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.CafeScalarWhereWithAggregatesInput
    | Prisma.CafeScalarWhereWithAggregatesInput[];
  OR?: Prisma.CafeScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.CafeScalarWhereWithAggregatesInput
    | Prisma.CafeScalarWhereWithAggregatesInput[];
  id?: Prisma.BigIntWithAggregatesFilter<"Cafe"> | bigint | number;
  slug?: Prisma.StringWithAggregatesFilter<"Cafe"> | string;
  name?: Prisma.StringWithAggregatesFilter<"Cafe"> | string;
  address?: Prisma.StringWithAggregatesFilter<"Cafe"> | string;
  latitude?:
    | Prisma.DecimalNullableWithAggregatesFilter<"Cafe">
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  longitude?:
    | Prisma.DecimalNullableWithAggregatesFilter<"Cafe">
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  googleMapsUrl?:
    | Prisma.StringNullableWithAggregatesFilter<"Cafe">
    | string
    | null;
  instagramUrl?:
    | Prisma.StringNullableWithAggregatesFilter<"Cafe">
    | string
    | null;
  wifi?: Prisma.BoolWithAggregatesFilter<"Cafe"> | boolean;
  parking?: Prisma.StringNullableWithAggregatesFilter<"Cafe"> | string | null;
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Cafe"> | Date | string;
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Cafe"> | Date | string;
};

export type CafeCreateInput = {
  id?: bigint | number;
  slug: string;
  name: string;
  address: string;
  latitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  longitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  googleMapsUrl?: string | null;
  instagramUrl?: string | null;
  wifi?: boolean;
  parking?: string | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  openingHours?: Prisma.OpeningHourCreateNestedManyWithoutCafeInput;
  paymentMethods?: Prisma.CafePaymentMethodCreateNestedManyWithoutCafeInput;
};

export type CafeUncheckedCreateInput = {
  id?: bigint | number;
  slug: string;
  name: string;
  address: string;
  latitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  longitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  googleMapsUrl?: string | null;
  instagramUrl?: string | null;
  wifi?: boolean;
  parking?: string | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  openingHours?: Prisma.OpeningHourUncheckedCreateNestedManyWithoutCafeInput;
  paymentMethods?: Prisma.CafePaymentMethodUncheckedCreateNestedManyWithoutCafeInput;
};

export type CafeUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number;
  slug?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  address?: Prisma.StringFieldUpdateOperationsInput | string;
  latitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  longitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  googleMapsUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  instagramUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  wifi?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  parking?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  openingHours?: Prisma.OpeningHourUpdateManyWithoutCafeNestedInput;
  paymentMethods?: Prisma.CafePaymentMethodUpdateManyWithoutCafeNestedInput;
};

export type CafeUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number;
  slug?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  address?: Prisma.StringFieldUpdateOperationsInput | string;
  latitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  longitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  googleMapsUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  instagramUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  wifi?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  parking?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  openingHours?: Prisma.OpeningHourUncheckedUpdateManyWithoutCafeNestedInput;
  paymentMethods?: Prisma.CafePaymentMethodUncheckedUpdateManyWithoutCafeNestedInput;
};

export type CafeCreateManyInput = {
  id?: bigint | number;
  slug: string;
  name: string;
  address: string;
  latitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  longitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  googleMapsUrl?: string | null;
  instagramUrl?: string | null;
  wifi?: boolean;
  parking?: string | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
};

export type CafeUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number;
  slug?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  address?: Prisma.StringFieldUpdateOperationsInput | string;
  latitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  longitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  googleMapsUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  instagramUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  wifi?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  parking?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CafeUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number;
  slug?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  address?: Prisma.StringFieldUpdateOperationsInput | string;
  latitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  longitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  googleMapsUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  instagramUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  wifi?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  parking?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CafeOrderByRelevanceInput = {
  fields:
    | Prisma.CafeOrderByRelevanceFieldEnum
    | Prisma.CafeOrderByRelevanceFieldEnum[];
  sort: Prisma.SortOrder;
  search: string;
};

export type CafeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  slug?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  address?: Prisma.SortOrder;
  latitude?: Prisma.SortOrder;
  longitude?: Prisma.SortOrder;
  googleMapsUrl?: Prisma.SortOrder;
  instagramUrl?: Prisma.SortOrder;
  wifi?: Prisma.SortOrder;
  parking?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type CafeAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  latitude?: Prisma.SortOrder;
  longitude?: Prisma.SortOrder;
};

export type CafeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  slug?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  address?: Prisma.SortOrder;
  latitude?: Prisma.SortOrder;
  longitude?: Prisma.SortOrder;
  googleMapsUrl?: Prisma.SortOrder;
  instagramUrl?: Prisma.SortOrder;
  wifi?: Prisma.SortOrder;
  parking?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type CafeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  slug?: Prisma.SortOrder;
  name?: Prisma.SortOrder;
  address?: Prisma.SortOrder;
  latitude?: Prisma.SortOrder;
  longitude?: Prisma.SortOrder;
  googleMapsUrl?: Prisma.SortOrder;
  instagramUrl?: Prisma.SortOrder;
  wifi?: Prisma.SortOrder;
  parking?: Prisma.SortOrder;
  createdAt?: Prisma.SortOrder;
  updatedAt?: Prisma.SortOrder;
};

export type CafeSumOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  latitude?: Prisma.SortOrder;
  longitude?: Prisma.SortOrder;
};

export type CafeScalarRelationFilter = {
  is?: Prisma.CafeWhereInput;
  isNot?: Prisma.CafeWhereInput;
};

export type BigIntFieldUpdateOperationsInput = {
  set?: bigint | number;
  increment?: bigint | number;
  decrement?: bigint | number;
  multiply?: bigint | number;
  divide?: bigint | number;
};

export type StringFieldUpdateOperationsInput = {
  set?: string;
};

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string;
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string;
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string;
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string;
};

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null;
};

export type BoolFieldUpdateOperationsInput = {
  set?: boolean;
};

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string;
};

export type CafeCreateNestedOneWithoutOpeningHoursInput = {
  create?: Prisma.XOR<
    Prisma.CafeCreateWithoutOpeningHoursInput,
    Prisma.CafeUncheckedCreateWithoutOpeningHoursInput
  >;
  connectOrCreate?: Prisma.CafeCreateOrConnectWithoutOpeningHoursInput;
  connect?: Prisma.CafeWhereUniqueInput;
};

export type CafeUpdateOneRequiredWithoutOpeningHoursNestedInput = {
  create?: Prisma.XOR<
    Prisma.CafeCreateWithoutOpeningHoursInput,
    Prisma.CafeUncheckedCreateWithoutOpeningHoursInput
  >;
  connectOrCreate?: Prisma.CafeCreateOrConnectWithoutOpeningHoursInput;
  upsert?: Prisma.CafeUpsertWithoutOpeningHoursInput;
  connect?: Prisma.CafeWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.CafeUpdateToOneWithWhereWithoutOpeningHoursInput,
      Prisma.CafeUpdateWithoutOpeningHoursInput
    >,
    Prisma.CafeUncheckedUpdateWithoutOpeningHoursInput
  >;
};

export type CafeCreateNestedOneWithoutPaymentMethodsInput = {
  create?: Prisma.XOR<
    Prisma.CafeCreateWithoutPaymentMethodsInput,
    Prisma.CafeUncheckedCreateWithoutPaymentMethodsInput
  >;
  connectOrCreate?: Prisma.CafeCreateOrConnectWithoutPaymentMethodsInput;
  connect?: Prisma.CafeWhereUniqueInput;
};

export type CafeUpdateOneRequiredWithoutPaymentMethodsNestedInput = {
  create?: Prisma.XOR<
    Prisma.CafeCreateWithoutPaymentMethodsInput,
    Prisma.CafeUncheckedCreateWithoutPaymentMethodsInput
  >;
  connectOrCreate?: Prisma.CafeCreateOrConnectWithoutPaymentMethodsInput;
  upsert?: Prisma.CafeUpsertWithoutPaymentMethodsInput;
  connect?: Prisma.CafeWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.CafeUpdateToOneWithWhereWithoutPaymentMethodsInput,
      Prisma.CafeUpdateWithoutPaymentMethodsInput
    >,
    Prisma.CafeUncheckedUpdateWithoutPaymentMethodsInput
  >;
};

export type CafeCreateWithoutOpeningHoursInput = {
  id?: bigint | number;
  slug: string;
  name: string;
  address: string;
  latitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  longitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  googleMapsUrl?: string | null;
  instagramUrl?: string | null;
  wifi?: boolean;
  parking?: string | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  paymentMethods?: Prisma.CafePaymentMethodCreateNestedManyWithoutCafeInput;
};

export type CafeUncheckedCreateWithoutOpeningHoursInput = {
  id?: bigint | number;
  slug: string;
  name: string;
  address: string;
  latitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  longitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  googleMapsUrl?: string | null;
  instagramUrl?: string | null;
  wifi?: boolean;
  parking?: string | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  paymentMethods?: Prisma.CafePaymentMethodUncheckedCreateNestedManyWithoutCafeInput;
};

export type CafeCreateOrConnectWithoutOpeningHoursInput = {
  where: Prisma.CafeWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.CafeCreateWithoutOpeningHoursInput,
    Prisma.CafeUncheckedCreateWithoutOpeningHoursInput
  >;
};

export type CafeUpsertWithoutOpeningHoursInput = {
  update: Prisma.XOR<
    Prisma.CafeUpdateWithoutOpeningHoursInput,
    Prisma.CafeUncheckedUpdateWithoutOpeningHoursInput
  >;
  create: Prisma.XOR<
    Prisma.CafeCreateWithoutOpeningHoursInput,
    Prisma.CafeUncheckedCreateWithoutOpeningHoursInput
  >;
  where?: Prisma.CafeWhereInput;
};

export type CafeUpdateToOneWithWhereWithoutOpeningHoursInput = {
  where?: Prisma.CafeWhereInput;
  data: Prisma.XOR<
    Prisma.CafeUpdateWithoutOpeningHoursInput,
    Prisma.CafeUncheckedUpdateWithoutOpeningHoursInput
  >;
};

export type CafeUpdateWithoutOpeningHoursInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number;
  slug?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  address?: Prisma.StringFieldUpdateOperationsInput | string;
  latitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  longitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  googleMapsUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  instagramUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  wifi?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  parking?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  paymentMethods?: Prisma.CafePaymentMethodUpdateManyWithoutCafeNestedInput;
};

export type CafeUncheckedUpdateWithoutOpeningHoursInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number;
  slug?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  address?: Prisma.StringFieldUpdateOperationsInput | string;
  latitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  longitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  googleMapsUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  instagramUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  wifi?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  parking?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  paymentMethods?: Prisma.CafePaymentMethodUncheckedUpdateManyWithoutCafeNestedInput;
};

export type CafeCreateWithoutPaymentMethodsInput = {
  id?: bigint | number;
  slug: string;
  name: string;
  address: string;
  latitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  longitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  googleMapsUrl?: string | null;
  instagramUrl?: string | null;
  wifi?: boolean;
  parking?: string | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  openingHours?: Prisma.OpeningHourCreateNestedManyWithoutCafeInput;
};

export type CafeUncheckedCreateWithoutPaymentMethodsInput = {
  id?: bigint | number;
  slug: string;
  name: string;
  address: string;
  latitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  longitude?: runtime.Decimal | runtime.DecimalJsLike | number | string | null;
  googleMapsUrl?: string | null;
  instagramUrl?: string | null;
  wifi?: boolean;
  parking?: string | null;
  createdAt?: Date | string;
  updatedAt?: Date | string;
  openingHours?: Prisma.OpeningHourUncheckedCreateNestedManyWithoutCafeInput;
};

export type CafeCreateOrConnectWithoutPaymentMethodsInput = {
  where: Prisma.CafeWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.CafeCreateWithoutPaymentMethodsInput,
    Prisma.CafeUncheckedCreateWithoutPaymentMethodsInput
  >;
};

export type CafeUpsertWithoutPaymentMethodsInput = {
  update: Prisma.XOR<
    Prisma.CafeUpdateWithoutPaymentMethodsInput,
    Prisma.CafeUncheckedUpdateWithoutPaymentMethodsInput
  >;
  create: Prisma.XOR<
    Prisma.CafeCreateWithoutPaymentMethodsInput,
    Prisma.CafeUncheckedCreateWithoutPaymentMethodsInput
  >;
  where?: Prisma.CafeWhereInput;
};

export type CafeUpdateToOneWithWhereWithoutPaymentMethodsInput = {
  where?: Prisma.CafeWhereInput;
  data: Prisma.XOR<
    Prisma.CafeUpdateWithoutPaymentMethodsInput,
    Prisma.CafeUncheckedUpdateWithoutPaymentMethodsInput
  >;
};

export type CafeUpdateWithoutPaymentMethodsInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number;
  slug?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  address?: Prisma.StringFieldUpdateOperationsInput | string;
  latitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  longitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  googleMapsUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  instagramUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  wifi?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  parking?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  openingHours?: Prisma.OpeningHourUpdateManyWithoutCafeNestedInput;
};

export type CafeUncheckedUpdateWithoutPaymentMethodsInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number;
  slug?: Prisma.StringFieldUpdateOperationsInput | string;
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  address?: Prisma.StringFieldUpdateOperationsInput | string;
  latitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  longitude?:
    | Prisma.NullableDecimalFieldUpdateOperationsInput
    | runtime.Decimal
    | runtime.DecimalJsLike
    | number
    | string
    | null;
  googleMapsUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  instagramUrl?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  wifi?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  parking?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  openingHours?: Prisma.OpeningHourUncheckedUpdateManyWithoutCafeNestedInput;
};

/**
 * Count Type CafeCountOutputType
 */

export type CafeCountOutputType = {
  openingHours: number;
  paymentMethods: number;
};

export type CafeCountOutputTypeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  openingHours?: boolean | CafeCountOutputTypeCountOpeningHoursArgs;
  paymentMethods?: boolean | CafeCountOutputTypeCountPaymentMethodsArgs;
};

/**
 * CafeCountOutputType without action
 */
export type CafeCountOutputTypeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the CafeCountOutputType
   */
  select?: Prisma.CafeCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * CafeCountOutputType without action
 */
export type CafeCountOutputTypeCountOpeningHoursArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  where?: Prisma.OpeningHourWhereInput;
};

/**
 * CafeCountOutputType without action
 */
export type CafeCountOutputTypeCountPaymentMethodsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  where?: Prisma.CafePaymentMethodWhereInput;
};

export type CafeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    slug?: boolean;
    name?: boolean;
    address?: boolean;
    latitude?: boolean;
    longitude?: boolean;
    googleMapsUrl?: boolean;
    instagramUrl?: boolean;
    wifi?: boolean;
    parking?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
    openingHours?: boolean | Prisma.Cafe$openingHoursArgs<ExtArgs>;
    paymentMethods?: boolean | Prisma.Cafe$paymentMethodsArgs<ExtArgs>;
    _count?: boolean | Prisma.CafeCountOutputTypeDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["cafe"]
>;

export type CafeSelectScalar = {
  id?: boolean;
  slug?: boolean;
  name?: boolean;
  address?: boolean;
  latitude?: boolean;
  longitude?: boolean;
  googleMapsUrl?: boolean;
  instagramUrl?: boolean;
  wifi?: boolean;
  parking?: boolean;
  createdAt?: boolean;
  updatedAt?: boolean;
};

export type CafeOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetOmit<
  | "id"
  | "slug"
  | "name"
  | "address"
  | "latitude"
  | "longitude"
  | "googleMapsUrl"
  | "instagramUrl"
  | "wifi"
  | "parking"
  | "createdAt"
  | "updatedAt",
  ExtArgs["result"]["cafe"]
>;
export type CafeInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  openingHours?: boolean | Prisma.Cafe$openingHoursArgs<ExtArgs>;
  paymentMethods?: boolean | Prisma.Cafe$paymentMethodsArgs<ExtArgs>;
  _count?: boolean | Prisma.CafeCountOutputTypeDefaultArgs<ExtArgs>;
};

export type $CafePayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  name: "Cafe";
  objects: {
    openingHours: Prisma.$OpeningHourPayload<ExtArgs>[];
    paymentMethods: Prisma.$CafePaymentMethodPayload<ExtArgs>[];
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: bigint;
      slug: string;
      name: string;
      address: string;
      latitude: runtime.Decimal | null;
      longitude: runtime.Decimal | null;
      googleMapsUrl: string | null;
      instagramUrl: string | null;
      wifi: boolean;
      parking: string | null;
      createdAt: Date;
      updatedAt: Date;
    },
    ExtArgs["result"]["cafe"]
  >;
  composites: {};
};

export type CafeGetPayload<
  S extends boolean | null | undefined | CafeDefaultArgs
> = runtime.Types.Result.GetResult<Prisma.$CafePayload, S>;

export type CafeCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = Omit<CafeFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
  select?: CafeCountAggregateInputType | true;
};

export interface CafeDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {}
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["Cafe"];
    meta: { name: "Cafe" };
  };
  /**
   * Find zero or one Cafe that matches the filter.
   * @param {CafeFindUniqueArgs} args - Arguments to find a Cafe
   * @example
   * // Get one Cafe
   * const cafe = await prisma.cafe.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CafeFindUniqueArgs>(
    args: Prisma.SelectSubset<T, CafeFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__CafeClient<
    runtime.Types.Result.GetResult<
      Prisma.$CafePayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one Cafe that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CafeFindUniqueOrThrowArgs} args - Arguments to find a Cafe
   * @example
   * // Get one Cafe
   * const cafe = await prisma.cafe.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CafeFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, CafeFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__CafeClient<
    runtime.Types.Result.GetResult<
      Prisma.$CafePayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first Cafe that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CafeFindFirstArgs} args - Arguments to find a Cafe
   * @example
   * // Get one Cafe
   * const cafe = await prisma.cafe.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CafeFindFirstArgs>(
    args?: Prisma.SelectSubset<T, CafeFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__CafeClient<
    runtime.Types.Result.GetResult<
      Prisma.$CafePayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first Cafe that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CafeFindFirstOrThrowArgs} args - Arguments to find a Cafe
   * @example
   * // Get one Cafe
   * const cafe = await prisma.cafe.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CafeFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, CafeFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__CafeClient<
    runtime.Types.Result.GetResult<
      Prisma.$CafePayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more Cafes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CafeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Cafes
   * const cafes = await prisma.cafe.findMany()
   *
   * // Get first 10 Cafes
   * const cafes = await prisma.cafe.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const cafeWithIdOnly = await prisma.cafe.findMany({ select: { id: true } })
   *
   */
  findMany<T extends CafeFindManyArgs>(
    args?: Prisma.SelectSubset<T, CafeFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$CafePayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >;

  /**
   * Create a Cafe.
   * @param {CafeCreateArgs} args - Arguments to create a Cafe.
   * @example
   * // Create one Cafe
   * const Cafe = await prisma.cafe.create({
   *   data: {
   *     // ... data to create a Cafe
   *   }
   * })
   *
   */
  create<T extends CafeCreateArgs>(
    args: Prisma.SelectSubset<T, CafeCreateArgs<ExtArgs>>
  ): Prisma.Prisma__CafeClient<
    runtime.Types.Result.GetResult<
      Prisma.$CafePayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many Cafes.
   * @param {CafeCreateManyArgs} args - Arguments to create many Cafes.
   * @example
   * // Create many Cafes
   * const cafe = await prisma.cafe.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends CafeCreateManyArgs>(
    args?: Prisma.SelectSubset<T, CafeCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Delete a Cafe.
   * @param {CafeDeleteArgs} args - Arguments to delete one Cafe.
   * @example
   * // Delete one Cafe
   * const Cafe = await prisma.cafe.delete({
   *   where: {
   *     // ... filter to delete one Cafe
   *   }
   * })
   *
   */
  delete<T extends CafeDeleteArgs>(
    args: Prisma.SelectSubset<T, CafeDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__CafeClient<
    runtime.Types.Result.GetResult<
      Prisma.$CafePayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one Cafe.
   * @param {CafeUpdateArgs} args - Arguments to update one Cafe.
   * @example
   * // Update one Cafe
   * const cafe = await prisma.cafe.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends CafeUpdateArgs>(
    args: Prisma.SelectSubset<T, CafeUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__CafeClient<
    runtime.Types.Result.GetResult<
      Prisma.$CafePayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more Cafes.
   * @param {CafeDeleteManyArgs} args - Arguments to filter Cafes to delete.
   * @example
   * // Delete a few Cafes
   * const { count } = await prisma.cafe.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends CafeDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, CafeDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more Cafes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CafeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Cafes
   * const cafe = await prisma.cafe.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends CafeUpdateManyArgs>(
    args: Prisma.SelectSubset<T, CafeUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create or update one Cafe.
   * @param {CafeUpsertArgs} args - Arguments to update or create a Cafe.
   * @example
   * // Update or create a Cafe
   * const cafe = await prisma.cafe.upsert({
   *   create: {
   *     // ... data to create a Cafe
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Cafe we want to update
   *   }
   * })
   */
  upsert<T extends CafeUpsertArgs>(
    args: Prisma.SelectSubset<T, CafeUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__CafeClient<
    runtime.Types.Result.GetResult<
      Prisma.$CafePayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of Cafes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CafeCountArgs} args - Arguments to filter Cafes to count.
   * @example
   * // Count the number of Cafes
   * const count = await prisma.cafe.count({
   *   where: {
   *     // ... the filter for the Cafes we want to count
   *   }
   * })
   **/
  count<T extends CafeCountArgs>(
    args?: Prisma.Subset<T, CafeCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<T["select"], CafeCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a Cafe.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CafeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends CafeAggregateArgs>(
    args: Prisma.Subset<T, CafeAggregateArgs>
  ): Prisma.PrismaPromise<GetCafeAggregateType<T>>;

  /**
   * Group by Cafe.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CafeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends CafeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CafeGroupByArgs["orderBy"] }
      : { orderBy?: CafeGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
            ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
            : [Error, "Field ", P, ` in "having" needs to be provided in "by"`];
        }[HavingFields]
      : "take" extends Prisma.Keys<T>
      ? "orderBy" extends Prisma.Keys<T>
        ? ByValid extends Prisma.True
          ? {}
          : {
              [P in OrderFields]: P extends ByFields
                ? never
                : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
            }[OrderFields]
        : 'Error: If you provide "take", you also need to provide "orderBy"'
      : "skip" extends Prisma.Keys<T>
      ? "orderBy" extends Prisma.Keys<T>
        ? ByValid extends Prisma.True
          ? {}
          : {
              [P in OrderFields]: P extends ByFields
                ? never
                : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
            }[OrderFields]
        : 'Error: If you provide "skip", you also need to provide "orderBy"'
      : ByValid extends Prisma.True
      ? {}
      : {
          [P in OrderFields]: P extends ByFields
            ? never
            : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
        }[OrderFields]
  >(
    args: Prisma.SubsetIntersection<T, CafeGroupByArgs, OrderByArg> &
      InputErrors
  ): {} extends InputErrors
    ? GetCafeGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the Cafe model
   */
  readonly fields: CafeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Cafe.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CafeClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {}
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  openingHours<T extends Prisma.Cafe$openingHoursArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.Cafe$openingHoursArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$OpeningHourPayload<ExtArgs>,
        T,
        "findMany",
        GlobalOmitOptions
      >
    | Null
  >;
  paymentMethods<T extends Prisma.Cafe$paymentMethodsArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.Cafe$paymentMethodsArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$CafePaymentMethodPayload<ExtArgs>,
        T,
        "findMany",
        GlobalOmitOptions
      >
    | Null
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the Cafe model
 */
export interface CafeFieldRefs {
  readonly id: Prisma.FieldRef<"Cafe", "BigInt">;
  readonly slug: Prisma.FieldRef<"Cafe", "String">;
  readonly name: Prisma.FieldRef<"Cafe", "String">;
  readonly address: Prisma.FieldRef<"Cafe", "String">;
  readonly latitude: Prisma.FieldRef<"Cafe", "Decimal">;
  readonly longitude: Prisma.FieldRef<"Cafe", "Decimal">;
  readonly googleMapsUrl: Prisma.FieldRef<"Cafe", "String">;
  readonly instagramUrl: Prisma.FieldRef<"Cafe", "String">;
  readonly wifi: Prisma.FieldRef<"Cafe", "Boolean">;
  readonly parking: Prisma.FieldRef<"Cafe", "String">;
  readonly createdAt: Prisma.FieldRef<"Cafe", "DateTime">;
  readonly updatedAt: Prisma.FieldRef<"Cafe", "DateTime">;
}

// Custom InputTypes
/**
 * Cafe findUnique
 */
export type CafeFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the Cafe
   */
  select?: Prisma.CafeSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Cafe
   */
  omit?: Prisma.CafeOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafeInclude<ExtArgs> | null;
  /**
   * Filter, which Cafe to fetch.
   */
  where: Prisma.CafeWhereUniqueInput;
};

/**
 * Cafe findUniqueOrThrow
 */
export type CafeFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the Cafe
   */
  select?: Prisma.CafeSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Cafe
   */
  omit?: Prisma.CafeOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafeInclude<ExtArgs> | null;
  /**
   * Filter, which Cafe to fetch.
   */
  where: Prisma.CafeWhereUniqueInput;
};

/**
 * Cafe findFirst
 */
export type CafeFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the Cafe
   */
  select?: Prisma.CafeSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Cafe
   */
  omit?: Prisma.CafeOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafeInclude<ExtArgs> | null;
  /**
   * Filter, which Cafe to fetch.
   */
  where?: Prisma.CafeWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Cafes to fetch.
   */
  orderBy?:
    | Prisma.CafeOrderByWithRelationInput
    | Prisma.CafeOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Cafes.
   */
  cursor?: Prisma.CafeWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Cafes from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Cafes.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Cafes.
   */
  distinct?: Prisma.CafeScalarFieldEnum | Prisma.CafeScalarFieldEnum[];
};

/**
 * Cafe findFirstOrThrow
 */
export type CafeFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the Cafe
   */
  select?: Prisma.CafeSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Cafe
   */
  omit?: Prisma.CafeOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafeInclude<ExtArgs> | null;
  /**
   * Filter, which Cafe to fetch.
   */
  where?: Prisma.CafeWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Cafes to fetch.
   */
  orderBy?:
    | Prisma.CafeOrderByWithRelationInput
    | Prisma.CafeOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Cafes.
   */
  cursor?: Prisma.CafeWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Cafes from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Cafes.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Cafes.
   */
  distinct?: Prisma.CafeScalarFieldEnum | Prisma.CafeScalarFieldEnum[];
};

/**
 * Cafe findMany
 */
export type CafeFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the Cafe
   */
  select?: Prisma.CafeSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Cafe
   */
  omit?: Prisma.CafeOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafeInclude<ExtArgs> | null;
  /**
   * Filter, which Cafes to fetch.
   */
  where?: Prisma.CafeWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Cafes to fetch.
   */
  orderBy?:
    | Prisma.CafeOrderByWithRelationInput
    | Prisma.CafeOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing Cafes.
   */
  cursor?: Prisma.CafeWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Cafes from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Cafes.
   */
  skip?: number;
  distinct?: Prisma.CafeScalarFieldEnum | Prisma.CafeScalarFieldEnum[];
};

/**
 * Cafe create
 */
export type CafeCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the Cafe
   */
  select?: Prisma.CafeSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Cafe
   */
  omit?: Prisma.CafeOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafeInclude<ExtArgs> | null;
  /**
   * The data needed to create a Cafe.
   */
  data: Prisma.XOR<Prisma.CafeCreateInput, Prisma.CafeUncheckedCreateInput>;
};

/**
 * Cafe createMany
 */
export type CafeCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * The data used to create many Cafes.
   */
  data: Prisma.CafeCreateManyInput | Prisma.CafeCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * Cafe update
 */
export type CafeUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the Cafe
   */
  select?: Prisma.CafeSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Cafe
   */
  omit?: Prisma.CafeOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafeInclude<ExtArgs> | null;
  /**
   * The data needed to update a Cafe.
   */
  data: Prisma.XOR<Prisma.CafeUpdateInput, Prisma.CafeUncheckedUpdateInput>;
  /**
   * Choose, which Cafe to update.
   */
  where: Prisma.CafeWhereUniqueInput;
};

/**
 * Cafe updateMany
 */
export type CafeUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * The data used to update Cafes.
   */
  data: Prisma.XOR<
    Prisma.CafeUpdateManyMutationInput,
    Prisma.CafeUncheckedUpdateManyInput
  >;
  /**
   * Filter which Cafes to update
   */
  where?: Prisma.CafeWhereInput;
  /**
   * Limit how many Cafes to update.
   */
  limit?: number;
};

/**
 * Cafe upsert
 */
export type CafeUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the Cafe
   */
  select?: Prisma.CafeSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Cafe
   */
  omit?: Prisma.CafeOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafeInclude<ExtArgs> | null;
  /**
   * The filter to search for the Cafe to update in case it exists.
   */
  where: Prisma.CafeWhereUniqueInput;
  /**
   * In case the Cafe found by the `where` argument doesn't exist, create a new Cafe with this data.
   */
  create: Prisma.XOR<Prisma.CafeCreateInput, Prisma.CafeUncheckedCreateInput>;
  /**
   * In case the Cafe was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CafeUpdateInput, Prisma.CafeUncheckedUpdateInput>;
};

/**
 * Cafe delete
 */
export type CafeDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the Cafe
   */
  select?: Prisma.CafeSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Cafe
   */
  omit?: Prisma.CafeOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafeInclude<ExtArgs> | null;
  /**
   * Filter which Cafe to delete.
   */
  where: Prisma.CafeWhereUniqueInput;
};

/**
 * Cafe deleteMany
 */
export type CafeDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Filter which Cafes to delete
   */
  where?: Prisma.CafeWhereInput;
  /**
   * Limit how many Cafes to delete.
   */
  limit?: number;
};

/**
 * Cafe.openingHours
 */
export type Cafe$openingHoursArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the OpeningHour
   */
  select?: Prisma.OpeningHourSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the OpeningHour
   */
  omit?: Prisma.OpeningHourOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OpeningHourInclude<ExtArgs> | null;
  where?: Prisma.OpeningHourWhereInput;
  orderBy?:
    | Prisma.OpeningHourOrderByWithRelationInput
    | Prisma.OpeningHourOrderByWithRelationInput[];
  cursor?: Prisma.OpeningHourWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?:
    | Prisma.OpeningHourScalarFieldEnum
    | Prisma.OpeningHourScalarFieldEnum[];
};

/**
 * Cafe.paymentMethods
 */
export type Cafe$paymentMethodsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the CafePaymentMethod
   */
  select?: Prisma.CafePaymentMethodSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CafePaymentMethod
   */
  omit?: Prisma.CafePaymentMethodOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafePaymentMethodInclude<ExtArgs> | null;
  where?: Prisma.CafePaymentMethodWhereInput;
  orderBy?:
    | Prisma.CafePaymentMethodOrderByWithRelationInput
    | Prisma.CafePaymentMethodOrderByWithRelationInput[];
  cursor?: Prisma.CafePaymentMethodWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?:
    | Prisma.CafePaymentMethodScalarFieldEnum
    | Prisma.CafePaymentMethodScalarFieldEnum[];
};

/**
 * Cafe without action
 */
export type CafeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the Cafe
   */
  select?: Prisma.CafeSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Cafe
   */
  omit?: Prisma.CafeOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafeInclude<ExtArgs> | null;
};
