
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CafePaymentMethod` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CafePaymentMethod
 * 
 */
export type CafePaymentMethodModel = runtime.Types.Result.DefaultSelection<Prisma.$CafePaymentMethodPayload>

export type AggregateCafePaymentMethod = {
  _count: CafePaymentMethodCountAggregateOutputType | null
  _avg: CafePaymentMethodAvgAggregateOutputType | null
  _sum: CafePaymentMethodSumAggregateOutputType | null
  _min: CafePaymentMethodMinAggregateOutputType | null
  _max: CafePaymentMethodMaxAggregateOutputType | null
}

export type CafePaymentMethodAvgAggregateOutputType = {
  cafeId: number | null
  paymentMethodId: number | null
}

export type CafePaymentMethodSumAggregateOutputType = {
  cafeId: bigint | null
  paymentMethodId: bigint | null
}

export type CafePaymentMethodMinAggregateOutputType = {
  cafeId: bigint | null
  paymentMethodId: bigint | null
}

export type CafePaymentMethodMaxAggregateOutputType = {
  cafeId: bigint | null
  paymentMethodId: bigint | null
}

export type CafePaymentMethodCountAggregateOutputType = {
  cafeId: number
  paymentMethodId: number
  _all: number
}


export type CafePaymentMethodAvgAggregateInputType = {
  cafeId?: true
  paymentMethodId?: true
}

export type CafePaymentMethodSumAggregateInputType = {
  cafeId?: true
  paymentMethodId?: true
}

export type CafePaymentMethodMinAggregateInputType = {
  cafeId?: true
  paymentMethodId?: true
}

export type CafePaymentMethodMaxAggregateInputType = {
  cafeId?: true
  paymentMethodId?: true
}

export type CafePaymentMethodCountAggregateInputType = {
  cafeId?: true
  paymentMethodId?: true
  _all?: true
}

export type CafePaymentMethodAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CafePaymentMethod to aggregate.
   */
  where?: Prisma.CafePaymentMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CafePaymentMethods to fetch.
   */
  orderBy?: Prisma.CafePaymentMethodOrderByWithRelationInput | Prisma.CafePaymentMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CafePaymentMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CafePaymentMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CafePaymentMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CafePaymentMethods
  **/
  _count?: true | CafePaymentMethodCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CafePaymentMethodAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CafePaymentMethodSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CafePaymentMethodMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CafePaymentMethodMaxAggregateInputType
}

export type GetCafePaymentMethodAggregateType<T extends CafePaymentMethodAggregateArgs> = {
      [P in keyof T & keyof AggregateCafePaymentMethod]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCafePaymentMethod[P]>
    : Prisma.GetScalarType<T[P], AggregateCafePaymentMethod[P]>
}




export type CafePaymentMethodGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CafePaymentMethodWhereInput
  orderBy?: Prisma.CafePaymentMethodOrderByWithAggregationInput | Prisma.CafePaymentMethodOrderByWithAggregationInput[]
  by: Prisma.CafePaymentMethodScalarFieldEnum[] | Prisma.CafePaymentMethodScalarFieldEnum
  having?: Prisma.CafePaymentMethodScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CafePaymentMethodCountAggregateInputType | true
  _avg?: CafePaymentMethodAvgAggregateInputType
  _sum?: CafePaymentMethodSumAggregateInputType
  _min?: CafePaymentMethodMinAggregateInputType
  _max?: CafePaymentMethodMaxAggregateInputType
}

export type CafePaymentMethodGroupByOutputType = {
  cafeId: bigint
  paymentMethodId: bigint
  _count: CafePaymentMethodCountAggregateOutputType | null
  _avg: CafePaymentMethodAvgAggregateOutputType | null
  _sum: CafePaymentMethodSumAggregateOutputType | null
  _min: CafePaymentMethodMinAggregateOutputType | null
  _max: CafePaymentMethodMaxAggregateOutputType | null
}

type GetCafePaymentMethodGroupByPayload<T extends CafePaymentMethodGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CafePaymentMethodGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CafePaymentMethodGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CafePaymentMethodGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CafePaymentMethodGroupByOutputType[P]>
      }
    >
  >



export type CafePaymentMethodWhereInput = {
  AND?: Prisma.CafePaymentMethodWhereInput | Prisma.CafePaymentMethodWhereInput[]
  OR?: Prisma.CafePaymentMethodWhereInput[]
  NOT?: Prisma.CafePaymentMethodWhereInput | Prisma.CafePaymentMethodWhereInput[]
  cafeId?: Prisma.BigIntFilter<"CafePaymentMethod"> | bigint | number
  paymentMethodId?: Prisma.BigIntFilter<"CafePaymentMethod"> | bigint | number
  cafe?: Prisma.XOR<Prisma.CafeScalarRelationFilter, Prisma.CafeWhereInput>
  paymentMethod?: Prisma.XOR<Prisma.PaymentMethodScalarRelationFilter, Prisma.PaymentMethodWhereInput>
}

export type CafePaymentMethodOrderByWithRelationInput = {
  cafeId?: Prisma.SortOrder
  paymentMethodId?: Prisma.SortOrder
  cafe?: Prisma.CafeOrderByWithRelationInput
  paymentMethod?: Prisma.PaymentMethodOrderByWithRelationInput
}

export type CafePaymentMethodWhereUniqueInput = Prisma.AtLeast<{
  cafeId_paymentMethodId?: Prisma.CafePaymentMethodCafeIdPaymentMethodIdCompoundUniqueInput
  AND?: Prisma.CafePaymentMethodWhereInput | Prisma.CafePaymentMethodWhereInput[]
  OR?: Prisma.CafePaymentMethodWhereInput[]
  NOT?: Prisma.CafePaymentMethodWhereInput | Prisma.CafePaymentMethodWhereInput[]
  cafeId?: Prisma.BigIntFilter<"CafePaymentMethod"> | bigint | number
  paymentMethodId?: Prisma.BigIntFilter<"CafePaymentMethod"> | bigint | number
  cafe?: Prisma.XOR<Prisma.CafeScalarRelationFilter, Prisma.CafeWhereInput>
  paymentMethod?: Prisma.XOR<Prisma.PaymentMethodScalarRelationFilter, Prisma.PaymentMethodWhereInput>
}, "cafeId_paymentMethodId">

export type CafePaymentMethodOrderByWithAggregationInput = {
  cafeId?: Prisma.SortOrder
  paymentMethodId?: Prisma.SortOrder
  _count?: Prisma.CafePaymentMethodCountOrderByAggregateInput
  _avg?: Prisma.CafePaymentMethodAvgOrderByAggregateInput
  _max?: Prisma.CafePaymentMethodMaxOrderByAggregateInput
  _min?: Prisma.CafePaymentMethodMinOrderByAggregateInput
  _sum?: Prisma.CafePaymentMethodSumOrderByAggregateInput
}

export type CafePaymentMethodScalarWhereWithAggregatesInput = {
  AND?: Prisma.CafePaymentMethodScalarWhereWithAggregatesInput | Prisma.CafePaymentMethodScalarWhereWithAggregatesInput[]
  OR?: Prisma.CafePaymentMethodScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CafePaymentMethodScalarWhereWithAggregatesInput | Prisma.CafePaymentMethodScalarWhereWithAggregatesInput[]
  cafeId?: Prisma.BigIntWithAggregatesFilter<"CafePaymentMethod"> | bigint | number
  paymentMethodId?: Prisma.BigIntWithAggregatesFilter<"CafePaymentMethod"> | bigint | number
}

export type CafePaymentMethodCreateInput = {
  cafe: Prisma.CafeCreateNestedOneWithoutPaymentMethodsInput
  paymentMethod: Prisma.PaymentMethodCreateNestedOneWithoutCafesInput
}

export type CafePaymentMethodUncheckedCreateInput = {
  cafeId: bigint | number
  paymentMethodId: bigint | number
}

export type CafePaymentMethodUpdateInput = {
  cafe?: Prisma.CafeUpdateOneRequiredWithoutPaymentMethodsNestedInput
  paymentMethod?: Prisma.PaymentMethodUpdateOneRequiredWithoutCafesNestedInput
}

export type CafePaymentMethodUncheckedUpdateInput = {
  cafeId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  paymentMethodId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type CafePaymentMethodCreateManyInput = {
  cafeId: bigint | number
  paymentMethodId: bigint | number
}

export type CafePaymentMethodUpdateManyMutationInput = {

}

export type CafePaymentMethodUncheckedUpdateManyInput = {
  cafeId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  paymentMethodId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type CafePaymentMethodListRelationFilter = {
  every?: Prisma.CafePaymentMethodWhereInput
  some?: Prisma.CafePaymentMethodWhereInput
  none?: Prisma.CafePaymentMethodWhereInput
}

export type CafePaymentMethodOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CafePaymentMethodCafeIdPaymentMethodIdCompoundUniqueInput = {
  cafeId: bigint | number
  paymentMethodId: bigint | number
}

export type CafePaymentMethodCountOrderByAggregateInput = {
  cafeId?: Prisma.SortOrder
  paymentMethodId?: Prisma.SortOrder
}

export type CafePaymentMethodAvgOrderByAggregateInput = {
  cafeId?: Prisma.SortOrder
  paymentMethodId?: Prisma.SortOrder
}

export type CafePaymentMethodMaxOrderByAggregateInput = {
  cafeId?: Prisma.SortOrder
  paymentMethodId?: Prisma.SortOrder
}

export type CafePaymentMethodMinOrderByAggregateInput = {
  cafeId?: Prisma.SortOrder
  paymentMethodId?: Prisma.SortOrder
}

export type CafePaymentMethodSumOrderByAggregateInput = {
  cafeId?: Prisma.SortOrder
  paymentMethodId?: Prisma.SortOrder
}

export type CafePaymentMethodCreateNestedManyWithoutCafeInput = {
  create?: Prisma.XOR<Prisma.CafePaymentMethodCreateWithoutCafeInput, Prisma.CafePaymentMethodUncheckedCreateWithoutCafeInput> | Prisma.CafePaymentMethodCreateWithoutCafeInput[] | Prisma.CafePaymentMethodUncheckedCreateWithoutCafeInput[]
  connectOrCreate?: Prisma.CafePaymentMethodCreateOrConnectWithoutCafeInput | Prisma.CafePaymentMethodCreateOrConnectWithoutCafeInput[]
  createMany?: Prisma.CafePaymentMethodCreateManyCafeInputEnvelope
  connect?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
}

export type CafePaymentMethodUncheckedCreateNestedManyWithoutCafeInput = {
  create?: Prisma.XOR<Prisma.CafePaymentMethodCreateWithoutCafeInput, Prisma.CafePaymentMethodUncheckedCreateWithoutCafeInput> | Prisma.CafePaymentMethodCreateWithoutCafeInput[] | Prisma.CafePaymentMethodUncheckedCreateWithoutCafeInput[]
  connectOrCreate?: Prisma.CafePaymentMethodCreateOrConnectWithoutCafeInput | Prisma.CafePaymentMethodCreateOrConnectWithoutCafeInput[]
  createMany?: Prisma.CafePaymentMethodCreateManyCafeInputEnvelope
  connect?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
}

export type CafePaymentMethodUpdateManyWithoutCafeNestedInput = {
  create?: Prisma.XOR<Prisma.CafePaymentMethodCreateWithoutCafeInput, Prisma.CafePaymentMethodUncheckedCreateWithoutCafeInput> | Prisma.CafePaymentMethodCreateWithoutCafeInput[] | Prisma.CafePaymentMethodUncheckedCreateWithoutCafeInput[]
  connectOrCreate?: Prisma.CafePaymentMethodCreateOrConnectWithoutCafeInput | Prisma.CafePaymentMethodCreateOrConnectWithoutCafeInput[]
  upsert?: Prisma.CafePaymentMethodUpsertWithWhereUniqueWithoutCafeInput | Prisma.CafePaymentMethodUpsertWithWhereUniqueWithoutCafeInput[]
  createMany?: Prisma.CafePaymentMethodCreateManyCafeInputEnvelope
  set?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  disconnect?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  delete?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  connect?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  update?: Prisma.CafePaymentMethodUpdateWithWhereUniqueWithoutCafeInput | Prisma.CafePaymentMethodUpdateWithWhereUniqueWithoutCafeInput[]
  updateMany?: Prisma.CafePaymentMethodUpdateManyWithWhereWithoutCafeInput | Prisma.CafePaymentMethodUpdateManyWithWhereWithoutCafeInput[]
  deleteMany?: Prisma.CafePaymentMethodScalarWhereInput | Prisma.CafePaymentMethodScalarWhereInput[]
}

export type CafePaymentMethodUncheckedUpdateManyWithoutCafeNestedInput = {
  create?: Prisma.XOR<Prisma.CafePaymentMethodCreateWithoutCafeInput, Prisma.CafePaymentMethodUncheckedCreateWithoutCafeInput> | Prisma.CafePaymentMethodCreateWithoutCafeInput[] | Prisma.CafePaymentMethodUncheckedCreateWithoutCafeInput[]
  connectOrCreate?: Prisma.CafePaymentMethodCreateOrConnectWithoutCafeInput | Prisma.CafePaymentMethodCreateOrConnectWithoutCafeInput[]
  upsert?: Prisma.CafePaymentMethodUpsertWithWhereUniqueWithoutCafeInput | Prisma.CafePaymentMethodUpsertWithWhereUniqueWithoutCafeInput[]
  createMany?: Prisma.CafePaymentMethodCreateManyCafeInputEnvelope
  set?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  disconnect?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  delete?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  connect?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  update?: Prisma.CafePaymentMethodUpdateWithWhereUniqueWithoutCafeInput | Prisma.CafePaymentMethodUpdateWithWhereUniqueWithoutCafeInput[]
  updateMany?: Prisma.CafePaymentMethodUpdateManyWithWhereWithoutCafeInput | Prisma.CafePaymentMethodUpdateManyWithWhereWithoutCafeInput[]
  deleteMany?: Prisma.CafePaymentMethodScalarWhereInput | Prisma.CafePaymentMethodScalarWhereInput[]
}

export type CafePaymentMethodCreateNestedManyWithoutPaymentMethodInput = {
  create?: Prisma.XOR<Prisma.CafePaymentMethodCreateWithoutPaymentMethodInput, Prisma.CafePaymentMethodUncheckedCreateWithoutPaymentMethodInput> | Prisma.CafePaymentMethodCreateWithoutPaymentMethodInput[] | Prisma.CafePaymentMethodUncheckedCreateWithoutPaymentMethodInput[]
  connectOrCreate?: Prisma.CafePaymentMethodCreateOrConnectWithoutPaymentMethodInput | Prisma.CafePaymentMethodCreateOrConnectWithoutPaymentMethodInput[]
  createMany?: Prisma.CafePaymentMethodCreateManyPaymentMethodInputEnvelope
  connect?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
}

export type CafePaymentMethodUncheckedCreateNestedManyWithoutPaymentMethodInput = {
  create?: Prisma.XOR<Prisma.CafePaymentMethodCreateWithoutPaymentMethodInput, Prisma.CafePaymentMethodUncheckedCreateWithoutPaymentMethodInput> | Prisma.CafePaymentMethodCreateWithoutPaymentMethodInput[] | Prisma.CafePaymentMethodUncheckedCreateWithoutPaymentMethodInput[]
  connectOrCreate?: Prisma.CafePaymentMethodCreateOrConnectWithoutPaymentMethodInput | Prisma.CafePaymentMethodCreateOrConnectWithoutPaymentMethodInput[]
  createMany?: Prisma.CafePaymentMethodCreateManyPaymentMethodInputEnvelope
  connect?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
}

export type CafePaymentMethodUpdateManyWithoutPaymentMethodNestedInput = {
  create?: Prisma.XOR<Prisma.CafePaymentMethodCreateWithoutPaymentMethodInput, Prisma.CafePaymentMethodUncheckedCreateWithoutPaymentMethodInput> | Prisma.CafePaymentMethodCreateWithoutPaymentMethodInput[] | Prisma.CafePaymentMethodUncheckedCreateWithoutPaymentMethodInput[]
  connectOrCreate?: Prisma.CafePaymentMethodCreateOrConnectWithoutPaymentMethodInput | Prisma.CafePaymentMethodCreateOrConnectWithoutPaymentMethodInput[]
  upsert?: Prisma.CafePaymentMethodUpsertWithWhereUniqueWithoutPaymentMethodInput | Prisma.CafePaymentMethodUpsertWithWhereUniqueWithoutPaymentMethodInput[]
  createMany?: Prisma.CafePaymentMethodCreateManyPaymentMethodInputEnvelope
  set?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  disconnect?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  delete?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  connect?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  update?: Prisma.CafePaymentMethodUpdateWithWhereUniqueWithoutPaymentMethodInput | Prisma.CafePaymentMethodUpdateWithWhereUniqueWithoutPaymentMethodInput[]
  updateMany?: Prisma.CafePaymentMethodUpdateManyWithWhereWithoutPaymentMethodInput | Prisma.CafePaymentMethodUpdateManyWithWhereWithoutPaymentMethodInput[]
  deleteMany?: Prisma.CafePaymentMethodScalarWhereInput | Prisma.CafePaymentMethodScalarWhereInput[]
}

export type CafePaymentMethodUncheckedUpdateManyWithoutPaymentMethodNestedInput = {
  create?: Prisma.XOR<Prisma.CafePaymentMethodCreateWithoutPaymentMethodInput, Prisma.CafePaymentMethodUncheckedCreateWithoutPaymentMethodInput> | Prisma.CafePaymentMethodCreateWithoutPaymentMethodInput[] | Prisma.CafePaymentMethodUncheckedCreateWithoutPaymentMethodInput[]
  connectOrCreate?: Prisma.CafePaymentMethodCreateOrConnectWithoutPaymentMethodInput | Prisma.CafePaymentMethodCreateOrConnectWithoutPaymentMethodInput[]
  upsert?: Prisma.CafePaymentMethodUpsertWithWhereUniqueWithoutPaymentMethodInput | Prisma.CafePaymentMethodUpsertWithWhereUniqueWithoutPaymentMethodInput[]
  createMany?: Prisma.CafePaymentMethodCreateManyPaymentMethodInputEnvelope
  set?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  disconnect?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  delete?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  connect?: Prisma.CafePaymentMethodWhereUniqueInput | Prisma.CafePaymentMethodWhereUniqueInput[]
  update?: Prisma.CafePaymentMethodUpdateWithWhereUniqueWithoutPaymentMethodInput | Prisma.CafePaymentMethodUpdateWithWhereUniqueWithoutPaymentMethodInput[]
  updateMany?: Prisma.CafePaymentMethodUpdateManyWithWhereWithoutPaymentMethodInput | Prisma.CafePaymentMethodUpdateManyWithWhereWithoutPaymentMethodInput[]
  deleteMany?: Prisma.CafePaymentMethodScalarWhereInput | Prisma.CafePaymentMethodScalarWhereInput[]
}

export type CafePaymentMethodCreateWithoutCafeInput = {
  paymentMethod: Prisma.PaymentMethodCreateNestedOneWithoutCafesInput
}

export type CafePaymentMethodUncheckedCreateWithoutCafeInput = {
  paymentMethodId: bigint | number
}

export type CafePaymentMethodCreateOrConnectWithoutCafeInput = {
  where: Prisma.CafePaymentMethodWhereUniqueInput
  create: Prisma.XOR<Prisma.CafePaymentMethodCreateWithoutCafeInput, Prisma.CafePaymentMethodUncheckedCreateWithoutCafeInput>
}

export type CafePaymentMethodCreateManyCafeInputEnvelope = {
  data: Prisma.CafePaymentMethodCreateManyCafeInput | Prisma.CafePaymentMethodCreateManyCafeInput[]
  skipDuplicates?: boolean
}

export type CafePaymentMethodUpsertWithWhereUniqueWithoutCafeInput = {
  where: Prisma.CafePaymentMethodWhereUniqueInput
  update: Prisma.XOR<Prisma.CafePaymentMethodUpdateWithoutCafeInput, Prisma.CafePaymentMethodUncheckedUpdateWithoutCafeInput>
  create: Prisma.XOR<Prisma.CafePaymentMethodCreateWithoutCafeInput, Prisma.CafePaymentMethodUncheckedCreateWithoutCafeInput>
}

export type CafePaymentMethodUpdateWithWhereUniqueWithoutCafeInput = {
  where: Prisma.CafePaymentMethodWhereUniqueInput
  data: Prisma.XOR<Prisma.CafePaymentMethodUpdateWithoutCafeInput, Prisma.CafePaymentMethodUncheckedUpdateWithoutCafeInput>
}

export type CafePaymentMethodUpdateManyWithWhereWithoutCafeInput = {
  where: Prisma.CafePaymentMethodScalarWhereInput
  data: Prisma.XOR<Prisma.CafePaymentMethodUpdateManyMutationInput, Prisma.CafePaymentMethodUncheckedUpdateManyWithoutCafeInput>
}

export type CafePaymentMethodScalarWhereInput = {
  AND?: Prisma.CafePaymentMethodScalarWhereInput | Prisma.CafePaymentMethodScalarWhereInput[]
  OR?: Prisma.CafePaymentMethodScalarWhereInput[]
  NOT?: Prisma.CafePaymentMethodScalarWhereInput | Prisma.CafePaymentMethodScalarWhereInput[]
  cafeId?: Prisma.BigIntFilter<"CafePaymentMethod"> | bigint | number
  paymentMethodId?: Prisma.BigIntFilter<"CafePaymentMethod"> | bigint | number
}

export type CafePaymentMethodCreateWithoutPaymentMethodInput = {
  cafe: Prisma.CafeCreateNestedOneWithoutPaymentMethodsInput
}

export type CafePaymentMethodUncheckedCreateWithoutPaymentMethodInput = {
  cafeId: bigint | number
}

export type CafePaymentMethodCreateOrConnectWithoutPaymentMethodInput = {
  where: Prisma.CafePaymentMethodWhereUniqueInput
  create: Prisma.XOR<Prisma.CafePaymentMethodCreateWithoutPaymentMethodInput, Prisma.CafePaymentMethodUncheckedCreateWithoutPaymentMethodInput>
}

export type CafePaymentMethodCreateManyPaymentMethodInputEnvelope = {
  data: Prisma.CafePaymentMethodCreateManyPaymentMethodInput | Prisma.CafePaymentMethodCreateManyPaymentMethodInput[]
  skipDuplicates?: boolean
}

export type CafePaymentMethodUpsertWithWhereUniqueWithoutPaymentMethodInput = {
  where: Prisma.CafePaymentMethodWhereUniqueInput
  update: Prisma.XOR<Prisma.CafePaymentMethodUpdateWithoutPaymentMethodInput, Prisma.CafePaymentMethodUncheckedUpdateWithoutPaymentMethodInput>
  create: Prisma.XOR<Prisma.CafePaymentMethodCreateWithoutPaymentMethodInput, Prisma.CafePaymentMethodUncheckedCreateWithoutPaymentMethodInput>
}

export type CafePaymentMethodUpdateWithWhereUniqueWithoutPaymentMethodInput = {
  where: Prisma.CafePaymentMethodWhereUniqueInput
  data: Prisma.XOR<Prisma.CafePaymentMethodUpdateWithoutPaymentMethodInput, Prisma.CafePaymentMethodUncheckedUpdateWithoutPaymentMethodInput>
}

export type CafePaymentMethodUpdateManyWithWhereWithoutPaymentMethodInput = {
  where: Prisma.CafePaymentMethodScalarWhereInput
  data: Prisma.XOR<Prisma.CafePaymentMethodUpdateManyMutationInput, Prisma.CafePaymentMethodUncheckedUpdateManyWithoutPaymentMethodInput>
}

export type CafePaymentMethodCreateManyCafeInput = {
  paymentMethodId: bigint | number
}

export type CafePaymentMethodUpdateWithoutCafeInput = {
  paymentMethod?: Prisma.PaymentMethodUpdateOneRequiredWithoutCafesNestedInput
}

export type CafePaymentMethodUncheckedUpdateWithoutCafeInput = {
  paymentMethodId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type CafePaymentMethodUncheckedUpdateManyWithoutCafeInput = {
  paymentMethodId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type CafePaymentMethodCreateManyPaymentMethodInput = {
  cafeId: bigint | number
}

export type CafePaymentMethodUpdateWithoutPaymentMethodInput = {
  cafe?: Prisma.CafeUpdateOneRequiredWithoutPaymentMethodsNestedInput
}

export type CafePaymentMethodUncheckedUpdateWithoutPaymentMethodInput = {
  cafeId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type CafePaymentMethodUncheckedUpdateManyWithoutPaymentMethodInput = {
  cafeId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}



export type CafePaymentMethodSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  cafeId?: boolean
  paymentMethodId?: boolean
  cafe?: boolean | Prisma.CafeDefaultArgs<ExtArgs>
  paymentMethod?: boolean | Prisma.PaymentMethodDefaultArgs<ExtArgs>
}, ExtArgs["result"]["cafePaymentMethod"]>



export type CafePaymentMethodSelectScalar = {
  cafeId?: boolean
  paymentMethodId?: boolean
}

export type CafePaymentMethodOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"cafeId" | "paymentMethodId", ExtArgs["result"]["cafePaymentMethod"]>
export type CafePaymentMethodInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cafe?: boolean | Prisma.CafeDefaultArgs<ExtArgs>
  paymentMethod?: boolean | Prisma.PaymentMethodDefaultArgs<ExtArgs>
}

export type $CafePaymentMethodPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CafePaymentMethod"
  objects: {
    cafe: Prisma.$CafePayload<ExtArgs>
    paymentMethod: Prisma.$PaymentMethodPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    cafeId: bigint
    paymentMethodId: bigint
  }, ExtArgs["result"]["cafePaymentMethod"]>
  composites: {}
}

export type CafePaymentMethodGetPayload<S extends boolean | null | undefined | CafePaymentMethodDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CafePaymentMethodPayload, S>

export type CafePaymentMethodCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CafePaymentMethodFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CafePaymentMethodCountAggregateInputType | true
  }

export interface CafePaymentMethodDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CafePaymentMethod'], meta: { name: 'CafePaymentMethod' } }
  /**
   * Find zero or one CafePaymentMethod that matches the filter.
   * @param {CafePaymentMethodFindUniqueArgs} args - Arguments to find a CafePaymentMethod
   * @example
   * // Get one CafePaymentMethod
   * const cafePaymentMethod = await prisma.cafePaymentMethod.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CafePaymentMethodFindUniqueArgs>(args: Prisma.SelectSubset<T, CafePaymentMethodFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CafePaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$CafePaymentMethodPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CafePaymentMethod that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CafePaymentMethodFindUniqueOrThrowArgs} args - Arguments to find a CafePaymentMethod
   * @example
   * // Get one CafePaymentMethod
   * const cafePaymentMethod = await prisma.cafePaymentMethod.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CafePaymentMethodFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CafePaymentMethodFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CafePaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$CafePaymentMethodPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CafePaymentMethod that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CafePaymentMethodFindFirstArgs} args - Arguments to find a CafePaymentMethod
   * @example
   * // Get one CafePaymentMethod
   * const cafePaymentMethod = await prisma.cafePaymentMethod.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CafePaymentMethodFindFirstArgs>(args?: Prisma.SelectSubset<T, CafePaymentMethodFindFirstArgs<ExtArgs>>): Prisma.Prisma__CafePaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$CafePaymentMethodPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CafePaymentMethod that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CafePaymentMethodFindFirstOrThrowArgs} args - Arguments to find a CafePaymentMethod
   * @example
   * // Get one CafePaymentMethod
   * const cafePaymentMethod = await prisma.cafePaymentMethod.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CafePaymentMethodFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CafePaymentMethodFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CafePaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$CafePaymentMethodPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CafePaymentMethods that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CafePaymentMethodFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CafePaymentMethods
   * const cafePaymentMethods = await prisma.cafePaymentMethod.findMany()
   * 
   * // Get first 10 CafePaymentMethods
   * const cafePaymentMethods = await prisma.cafePaymentMethod.findMany({ take: 10 })
   * 
   * // Only select the `cafeId`
   * const cafePaymentMethodWithCafeIdOnly = await prisma.cafePaymentMethod.findMany({ select: { cafeId: true } })
   * 
   */
  findMany<T extends CafePaymentMethodFindManyArgs>(args?: Prisma.SelectSubset<T, CafePaymentMethodFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CafePaymentMethodPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CafePaymentMethod.
   * @param {CafePaymentMethodCreateArgs} args - Arguments to create a CafePaymentMethod.
   * @example
   * // Create one CafePaymentMethod
   * const CafePaymentMethod = await prisma.cafePaymentMethod.create({
   *   data: {
   *     // ... data to create a CafePaymentMethod
   *   }
   * })
   * 
   */
  create<T extends CafePaymentMethodCreateArgs>(args: Prisma.SelectSubset<T, CafePaymentMethodCreateArgs<ExtArgs>>): Prisma.Prisma__CafePaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$CafePaymentMethodPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CafePaymentMethods.
   * @param {CafePaymentMethodCreateManyArgs} args - Arguments to create many CafePaymentMethods.
   * @example
   * // Create many CafePaymentMethods
   * const cafePaymentMethod = await prisma.cafePaymentMethod.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CafePaymentMethodCreateManyArgs>(args?: Prisma.SelectSubset<T, CafePaymentMethodCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a CafePaymentMethod.
   * @param {CafePaymentMethodDeleteArgs} args - Arguments to delete one CafePaymentMethod.
   * @example
   * // Delete one CafePaymentMethod
   * const CafePaymentMethod = await prisma.cafePaymentMethod.delete({
   *   where: {
   *     // ... filter to delete one CafePaymentMethod
   *   }
   * })
   * 
   */
  delete<T extends CafePaymentMethodDeleteArgs>(args: Prisma.SelectSubset<T, CafePaymentMethodDeleteArgs<ExtArgs>>): Prisma.Prisma__CafePaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$CafePaymentMethodPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CafePaymentMethod.
   * @param {CafePaymentMethodUpdateArgs} args - Arguments to update one CafePaymentMethod.
   * @example
   * // Update one CafePaymentMethod
   * const cafePaymentMethod = await prisma.cafePaymentMethod.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CafePaymentMethodUpdateArgs>(args: Prisma.SelectSubset<T, CafePaymentMethodUpdateArgs<ExtArgs>>): Prisma.Prisma__CafePaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$CafePaymentMethodPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CafePaymentMethods.
   * @param {CafePaymentMethodDeleteManyArgs} args - Arguments to filter CafePaymentMethods to delete.
   * @example
   * // Delete a few CafePaymentMethods
   * const { count } = await prisma.cafePaymentMethod.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CafePaymentMethodDeleteManyArgs>(args?: Prisma.SelectSubset<T, CafePaymentMethodDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CafePaymentMethods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CafePaymentMethodUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CafePaymentMethods
   * const cafePaymentMethod = await prisma.cafePaymentMethod.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CafePaymentMethodUpdateManyArgs>(args: Prisma.SelectSubset<T, CafePaymentMethodUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one CafePaymentMethod.
   * @param {CafePaymentMethodUpsertArgs} args - Arguments to update or create a CafePaymentMethod.
   * @example
   * // Update or create a CafePaymentMethod
   * const cafePaymentMethod = await prisma.cafePaymentMethod.upsert({
   *   create: {
   *     // ... data to create a CafePaymentMethod
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CafePaymentMethod we want to update
   *   }
   * })
   */
  upsert<T extends CafePaymentMethodUpsertArgs>(args: Prisma.SelectSubset<T, CafePaymentMethodUpsertArgs<ExtArgs>>): Prisma.Prisma__CafePaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$CafePaymentMethodPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CafePaymentMethods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CafePaymentMethodCountArgs} args - Arguments to filter CafePaymentMethods to count.
   * @example
   * // Count the number of CafePaymentMethods
   * const count = await prisma.cafePaymentMethod.count({
   *   where: {
   *     // ... the filter for the CafePaymentMethods we want to count
   *   }
   * })
  **/
  count<T extends CafePaymentMethodCountArgs>(
    args?: Prisma.Subset<T, CafePaymentMethodCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CafePaymentMethodCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CafePaymentMethod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CafePaymentMethodAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CafePaymentMethodAggregateArgs>(args: Prisma.Subset<T, CafePaymentMethodAggregateArgs>): Prisma.PrismaPromise<GetCafePaymentMethodAggregateType<T>>

  /**
   * Group by CafePaymentMethod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CafePaymentMethodGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CafePaymentMethodGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CafePaymentMethodGroupByArgs['orderBy'] }
      : { orderBy?: CafePaymentMethodGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CafePaymentMethodGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCafePaymentMethodGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CafePaymentMethod model
 */
readonly fields: CafePaymentMethodFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CafePaymentMethod.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CafePaymentMethodClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  cafe<T extends Prisma.CafeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CafeDefaultArgs<ExtArgs>>): Prisma.Prisma__CafeClient<runtime.Types.Result.GetResult<Prisma.$CafePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  paymentMethod<T extends Prisma.PaymentMethodDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PaymentMethodDefaultArgs<ExtArgs>>): Prisma.Prisma__PaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$PaymentMethodPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CafePaymentMethod model
 */
export interface CafePaymentMethodFieldRefs {
  readonly cafeId: Prisma.FieldRef<"CafePaymentMethod", 'BigInt'>
  readonly paymentMethodId: Prisma.FieldRef<"CafePaymentMethod", 'BigInt'>
}
    

// Custom InputTypes
/**
 * CafePaymentMethod findUnique
 */
export type CafePaymentMethodFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CafePaymentMethod
   */
  select?: Prisma.CafePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CafePaymentMethod
   */
  omit?: Prisma.CafePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafePaymentMethodInclude<ExtArgs> | null
  /**
   * Filter, which CafePaymentMethod to fetch.
   */
  where: Prisma.CafePaymentMethodWhereUniqueInput
}

/**
 * CafePaymentMethod findUniqueOrThrow
 */
export type CafePaymentMethodFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CafePaymentMethod
   */
  select?: Prisma.CafePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CafePaymentMethod
   */
  omit?: Prisma.CafePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafePaymentMethodInclude<ExtArgs> | null
  /**
   * Filter, which CafePaymentMethod to fetch.
   */
  where: Prisma.CafePaymentMethodWhereUniqueInput
}

/**
 * CafePaymentMethod findFirst
 */
export type CafePaymentMethodFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CafePaymentMethod
   */
  select?: Prisma.CafePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CafePaymentMethod
   */
  omit?: Prisma.CafePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafePaymentMethodInclude<ExtArgs> | null
  /**
   * Filter, which CafePaymentMethod to fetch.
   */
  where?: Prisma.CafePaymentMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CafePaymentMethods to fetch.
   */
  orderBy?: Prisma.CafePaymentMethodOrderByWithRelationInput | Prisma.CafePaymentMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CafePaymentMethods.
   */
  cursor?: Prisma.CafePaymentMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CafePaymentMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CafePaymentMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CafePaymentMethods.
   */
  distinct?: Prisma.CafePaymentMethodScalarFieldEnum | Prisma.CafePaymentMethodScalarFieldEnum[]
}

/**
 * CafePaymentMethod findFirstOrThrow
 */
export type CafePaymentMethodFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CafePaymentMethod
   */
  select?: Prisma.CafePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CafePaymentMethod
   */
  omit?: Prisma.CafePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafePaymentMethodInclude<ExtArgs> | null
  /**
   * Filter, which CafePaymentMethod to fetch.
   */
  where?: Prisma.CafePaymentMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CafePaymentMethods to fetch.
   */
  orderBy?: Prisma.CafePaymentMethodOrderByWithRelationInput | Prisma.CafePaymentMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CafePaymentMethods.
   */
  cursor?: Prisma.CafePaymentMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CafePaymentMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CafePaymentMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CafePaymentMethods.
   */
  distinct?: Prisma.CafePaymentMethodScalarFieldEnum | Prisma.CafePaymentMethodScalarFieldEnum[]
}

/**
 * CafePaymentMethod findMany
 */
export type CafePaymentMethodFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CafePaymentMethod
   */
  select?: Prisma.CafePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CafePaymentMethod
   */
  omit?: Prisma.CafePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafePaymentMethodInclude<ExtArgs> | null
  /**
   * Filter, which CafePaymentMethods to fetch.
   */
  where?: Prisma.CafePaymentMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CafePaymentMethods to fetch.
   */
  orderBy?: Prisma.CafePaymentMethodOrderByWithRelationInput | Prisma.CafePaymentMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CafePaymentMethods.
   */
  cursor?: Prisma.CafePaymentMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CafePaymentMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CafePaymentMethods.
   */
  skip?: number
  distinct?: Prisma.CafePaymentMethodScalarFieldEnum | Prisma.CafePaymentMethodScalarFieldEnum[]
}

/**
 * CafePaymentMethod create
 */
export type CafePaymentMethodCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CafePaymentMethod
   */
  select?: Prisma.CafePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CafePaymentMethod
   */
  omit?: Prisma.CafePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafePaymentMethodInclude<ExtArgs> | null
  /**
   * The data needed to create a CafePaymentMethod.
   */
  data: Prisma.XOR<Prisma.CafePaymentMethodCreateInput, Prisma.CafePaymentMethodUncheckedCreateInput>
}

/**
 * CafePaymentMethod createMany
 */
export type CafePaymentMethodCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CafePaymentMethods.
   */
  data: Prisma.CafePaymentMethodCreateManyInput | Prisma.CafePaymentMethodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CafePaymentMethod update
 */
export type CafePaymentMethodUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CafePaymentMethod
   */
  select?: Prisma.CafePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CafePaymentMethod
   */
  omit?: Prisma.CafePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafePaymentMethodInclude<ExtArgs> | null
  /**
   * The data needed to update a CafePaymentMethod.
   */
  data: Prisma.XOR<Prisma.CafePaymentMethodUpdateInput, Prisma.CafePaymentMethodUncheckedUpdateInput>
  /**
   * Choose, which CafePaymentMethod to update.
   */
  where: Prisma.CafePaymentMethodWhereUniqueInput
}

/**
 * CafePaymentMethod updateMany
 */
export type CafePaymentMethodUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CafePaymentMethods.
   */
  data: Prisma.XOR<Prisma.CafePaymentMethodUpdateManyMutationInput, Prisma.CafePaymentMethodUncheckedUpdateManyInput>
  /**
   * Filter which CafePaymentMethods to update
   */
  where?: Prisma.CafePaymentMethodWhereInput
  /**
   * Limit how many CafePaymentMethods to update.
   */
  limit?: number
}

/**
 * CafePaymentMethod upsert
 */
export type CafePaymentMethodUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CafePaymentMethod
   */
  select?: Prisma.CafePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CafePaymentMethod
   */
  omit?: Prisma.CafePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafePaymentMethodInclude<ExtArgs> | null
  /**
   * The filter to search for the CafePaymentMethod to update in case it exists.
   */
  where: Prisma.CafePaymentMethodWhereUniqueInput
  /**
   * In case the CafePaymentMethod found by the `where` argument doesn't exist, create a new CafePaymentMethod with this data.
   */
  create: Prisma.XOR<Prisma.CafePaymentMethodCreateInput, Prisma.CafePaymentMethodUncheckedCreateInput>
  /**
   * In case the CafePaymentMethod was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CafePaymentMethodUpdateInput, Prisma.CafePaymentMethodUncheckedUpdateInput>
}

/**
 * CafePaymentMethod delete
 */
export type CafePaymentMethodDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CafePaymentMethod
   */
  select?: Prisma.CafePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CafePaymentMethod
   */
  omit?: Prisma.CafePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafePaymentMethodInclude<ExtArgs> | null
  /**
   * Filter which CafePaymentMethod to delete.
   */
  where: Prisma.CafePaymentMethodWhereUniqueInput
}

/**
 * CafePaymentMethod deleteMany
 */
export type CafePaymentMethodDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CafePaymentMethods to delete
   */
  where?: Prisma.CafePaymentMethodWhereInput
  /**
   * Limit how many CafePaymentMethods to delete.
   */
  limit?: number
}

/**
 * CafePaymentMethod without action
 */
export type CafePaymentMethodDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CafePaymentMethod
   */
  select?: Prisma.CafePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CafePaymentMethod
   */
  omit?: Prisma.CafePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafePaymentMethodInclude<ExtArgs> | null
}
