
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OpeningHour` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model OpeningHour
 * 
 */
export type OpeningHourModel = runtime.Types.Result.DefaultSelection<Prisma.$OpeningHourPayload>

export type AggregateOpeningHour = {
  _count: OpeningHourCountAggregateOutputType | null
  _avg: OpeningHourAvgAggregateOutputType | null
  _sum: OpeningHourSumAggregateOutputType | null
  _min: OpeningHourMinAggregateOutputType | null
  _max: OpeningHourMaxAggregateOutputType | null
}

export type OpeningHourAvgAggregateOutputType = {
  id: number | null
  cafeId: number | null
}

export type OpeningHourSumAggregateOutputType = {
  id: bigint | null
  cafeId: bigint | null
}

export type OpeningHourMinAggregateOutputType = {
  id: bigint | null
  cafeId: bigint | null
  dayOfWeek: string | null
  openTime: Date | null
  closeTime: Date | null
  isClosed: boolean | null
}

export type OpeningHourMaxAggregateOutputType = {
  id: bigint | null
  cafeId: bigint | null
  dayOfWeek: string | null
  openTime: Date | null
  closeTime: Date | null
  isClosed: boolean | null
}

export type OpeningHourCountAggregateOutputType = {
  id: number
  cafeId: number
  dayOfWeek: number
  openTime: number
  closeTime: number
  isClosed: number
  _all: number
}


export type OpeningHourAvgAggregateInputType = {
  id?: true
  cafeId?: true
}

export type OpeningHourSumAggregateInputType = {
  id?: true
  cafeId?: true
}

export type OpeningHourMinAggregateInputType = {
  id?: true
  cafeId?: true
  dayOfWeek?: true
  openTime?: true
  closeTime?: true
  isClosed?: true
}

export type OpeningHourMaxAggregateInputType = {
  id?: true
  cafeId?: true
  dayOfWeek?: true
  openTime?: true
  closeTime?: true
  isClosed?: true
}

export type OpeningHourCountAggregateInputType = {
  id?: true
  cafeId?: true
  dayOfWeek?: true
  openTime?: true
  closeTime?: true
  isClosed?: true
  _all?: true
}

export type OpeningHourAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OpeningHour to aggregate.
   */
  where?: Prisma.OpeningHourWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OpeningHours to fetch.
   */
  orderBy?: Prisma.OpeningHourOrderByWithRelationInput | Prisma.OpeningHourOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OpeningHourWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OpeningHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OpeningHours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OpeningHours
  **/
  _count?: true | OpeningHourCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: OpeningHourAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: OpeningHourSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OpeningHourMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OpeningHourMaxAggregateInputType
}

export type GetOpeningHourAggregateType<T extends OpeningHourAggregateArgs> = {
      [P in keyof T & keyof AggregateOpeningHour]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOpeningHour[P]>
    : Prisma.GetScalarType<T[P], AggregateOpeningHour[P]>
}




export type OpeningHourGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OpeningHourWhereInput
  orderBy?: Prisma.OpeningHourOrderByWithAggregationInput | Prisma.OpeningHourOrderByWithAggregationInput[]
  by: Prisma.OpeningHourScalarFieldEnum[] | Prisma.OpeningHourScalarFieldEnum
  having?: Prisma.OpeningHourScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OpeningHourCountAggregateInputType | true
  _avg?: OpeningHourAvgAggregateInputType
  _sum?: OpeningHourSumAggregateInputType
  _min?: OpeningHourMinAggregateInputType
  _max?: OpeningHourMaxAggregateInputType
}

export type OpeningHourGroupByOutputType = {
  id: bigint
  cafeId: bigint
  dayOfWeek: string
  openTime: Date
  closeTime: Date
  isClosed: boolean
  _count: OpeningHourCountAggregateOutputType | null
  _avg: OpeningHourAvgAggregateOutputType | null
  _sum: OpeningHourSumAggregateOutputType | null
  _min: OpeningHourMinAggregateOutputType | null
  _max: OpeningHourMaxAggregateOutputType | null
}

type GetOpeningHourGroupByPayload<T extends OpeningHourGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OpeningHourGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OpeningHourGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OpeningHourGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OpeningHourGroupByOutputType[P]>
      }
    >
  >



export type OpeningHourWhereInput = {
  AND?: Prisma.OpeningHourWhereInput | Prisma.OpeningHourWhereInput[]
  OR?: Prisma.OpeningHourWhereInput[]
  NOT?: Prisma.OpeningHourWhereInput | Prisma.OpeningHourWhereInput[]
  id?: Prisma.BigIntFilter<"OpeningHour"> | bigint | number
  cafeId?: Prisma.BigIntFilter<"OpeningHour"> | bigint | number
  dayOfWeek?: Prisma.StringFilter<"OpeningHour"> | string
  openTime?: Prisma.DateTimeFilter<"OpeningHour"> | Date | string
  closeTime?: Prisma.DateTimeFilter<"OpeningHour"> | Date | string
  isClosed?: Prisma.BoolFilter<"OpeningHour"> | boolean
  cafe?: Prisma.XOR<Prisma.CafeScalarRelationFilter, Prisma.CafeWhereInput>
}

export type OpeningHourOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  cafeId?: Prisma.SortOrder
  dayOfWeek?: Prisma.SortOrder
  openTime?: Prisma.SortOrder
  closeTime?: Prisma.SortOrder
  isClosed?: Prisma.SortOrder
  cafe?: Prisma.CafeOrderByWithRelationInput
  _relevance?: Prisma.OpeningHourOrderByRelevanceInput
}

export type OpeningHourWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  cafeId_dayOfWeek?: Prisma.OpeningHourCafeIdDayOfWeekCompoundUniqueInput
  AND?: Prisma.OpeningHourWhereInput | Prisma.OpeningHourWhereInput[]
  OR?: Prisma.OpeningHourWhereInput[]
  NOT?: Prisma.OpeningHourWhereInput | Prisma.OpeningHourWhereInput[]
  cafeId?: Prisma.BigIntFilter<"OpeningHour"> | bigint | number
  dayOfWeek?: Prisma.StringFilter<"OpeningHour"> | string
  openTime?: Prisma.DateTimeFilter<"OpeningHour"> | Date | string
  closeTime?: Prisma.DateTimeFilter<"OpeningHour"> | Date | string
  isClosed?: Prisma.BoolFilter<"OpeningHour"> | boolean
  cafe?: Prisma.XOR<Prisma.CafeScalarRelationFilter, Prisma.CafeWhereInput>
}, "id" | "cafeId_dayOfWeek">

export type OpeningHourOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  cafeId?: Prisma.SortOrder
  dayOfWeek?: Prisma.SortOrder
  openTime?: Prisma.SortOrder
  closeTime?: Prisma.SortOrder
  isClosed?: Prisma.SortOrder
  _count?: Prisma.OpeningHourCountOrderByAggregateInput
  _avg?: Prisma.OpeningHourAvgOrderByAggregateInput
  _max?: Prisma.OpeningHourMaxOrderByAggregateInput
  _min?: Prisma.OpeningHourMinOrderByAggregateInput
  _sum?: Prisma.OpeningHourSumOrderByAggregateInput
}

export type OpeningHourScalarWhereWithAggregatesInput = {
  AND?: Prisma.OpeningHourScalarWhereWithAggregatesInput | Prisma.OpeningHourScalarWhereWithAggregatesInput[]
  OR?: Prisma.OpeningHourScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OpeningHourScalarWhereWithAggregatesInput | Prisma.OpeningHourScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"OpeningHour"> | bigint | number
  cafeId?: Prisma.BigIntWithAggregatesFilter<"OpeningHour"> | bigint | number
  dayOfWeek?: Prisma.StringWithAggregatesFilter<"OpeningHour"> | string
  openTime?: Prisma.DateTimeWithAggregatesFilter<"OpeningHour"> | Date | string
  closeTime?: Prisma.DateTimeWithAggregatesFilter<"OpeningHour"> | Date | string
  isClosed?: Prisma.BoolWithAggregatesFilter<"OpeningHour"> | boolean
}

export type OpeningHourCreateInput = {
  id?: bigint | number
  dayOfWeek: string
  openTime: Date | string
  closeTime: Date | string
  isClosed?: boolean
  cafe: Prisma.CafeCreateNestedOneWithoutOpeningHoursInput
}

export type OpeningHourUncheckedCreateInput = {
  id?: bigint | number
  cafeId: bigint | number
  dayOfWeek: string
  openTime: Date | string
  closeTime: Date | string
  isClosed?: boolean
}

export type OpeningHourUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  dayOfWeek?: Prisma.StringFieldUpdateOperationsInput | string
  openTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closeTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isClosed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  cafe?: Prisma.CafeUpdateOneRequiredWithoutOpeningHoursNestedInput
}

export type OpeningHourUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  cafeId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  dayOfWeek?: Prisma.StringFieldUpdateOperationsInput | string
  openTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closeTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isClosed?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type OpeningHourCreateManyInput = {
  id?: bigint | number
  cafeId: bigint | number
  dayOfWeek: string
  openTime: Date | string
  closeTime: Date | string
  isClosed?: boolean
}

export type OpeningHourUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  dayOfWeek?: Prisma.StringFieldUpdateOperationsInput | string
  openTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closeTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isClosed?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type OpeningHourUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  cafeId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  dayOfWeek?: Prisma.StringFieldUpdateOperationsInput | string
  openTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closeTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isClosed?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type OpeningHourListRelationFilter = {
  every?: Prisma.OpeningHourWhereInput
  some?: Prisma.OpeningHourWhereInput
  none?: Prisma.OpeningHourWhereInput
}

export type OpeningHourOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OpeningHourOrderByRelevanceInput = {
  fields: Prisma.OpeningHourOrderByRelevanceFieldEnum | Prisma.OpeningHourOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type OpeningHourCafeIdDayOfWeekCompoundUniqueInput = {
  cafeId: bigint | number
  dayOfWeek: string
}

export type OpeningHourCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cafeId?: Prisma.SortOrder
  dayOfWeek?: Prisma.SortOrder
  openTime?: Prisma.SortOrder
  closeTime?: Prisma.SortOrder
  isClosed?: Prisma.SortOrder
}

export type OpeningHourAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cafeId?: Prisma.SortOrder
}

export type OpeningHourMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cafeId?: Prisma.SortOrder
  dayOfWeek?: Prisma.SortOrder
  openTime?: Prisma.SortOrder
  closeTime?: Prisma.SortOrder
  isClosed?: Prisma.SortOrder
}

export type OpeningHourMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cafeId?: Prisma.SortOrder
  dayOfWeek?: Prisma.SortOrder
  openTime?: Prisma.SortOrder
  closeTime?: Prisma.SortOrder
  isClosed?: Prisma.SortOrder
}

export type OpeningHourSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cafeId?: Prisma.SortOrder
}

export type OpeningHourCreateNestedManyWithoutCafeInput = {
  create?: Prisma.XOR<Prisma.OpeningHourCreateWithoutCafeInput, Prisma.OpeningHourUncheckedCreateWithoutCafeInput> | Prisma.OpeningHourCreateWithoutCafeInput[] | Prisma.OpeningHourUncheckedCreateWithoutCafeInput[]
  connectOrCreate?: Prisma.OpeningHourCreateOrConnectWithoutCafeInput | Prisma.OpeningHourCreateOrConnectWithoutCafeInput[]
  createMany?: Prisma.OpeningHourCreateManyCafeInputEnvelope
  connect?: Prisma.OpeningHourWhereUniqueInput | Prisma.OpeningHourWhereUniqueInput[]
}

export type OpeningHourUncheckedCreateNestedManyWithoutCafeInput = {
  create?: Prisma.XOR<Prisma.OpeningHourCreateWithoutCafeInput, Prisma.OpeningHourUncheckedCreateWithoutCafeInput> | Prisma.OpeningHourCreateWithoutCafeInput[] | Prisma.OpeningHourUncheckedCreateWithoutCafeInput[]
  connectOrCreate?: Prisma.OpeningHourCreateOrConnectWithoutCafeInput | Prisma.OpeningHourCreateOrConnectWithoutCafeInput[]
  createMany?: Prisma.OpeningHourCreateManyCafeInputEnvelope
  connect?: Prisma.OpeningHourWhereUniqueInput | Prisma.OpeningHourWhereUniqueInput[]
}

export type OpeningHourUpdateManyWithoutCafeNestedInput = {
  create?: Prisma.XOR<Prisma.OpeningHourCreateWithoutCafeInput, Prisma.OpeningHourUncheckedCreateWithoutCafeInput> | Prisma.OpeningHourCreateWithoutCafeInput[] | Prisma.OpeningHourUncheckedCreateWithoutCafeInput[]
  connectOrCreate?: Prisma.OpeningHourCreateOrConnectWithoutCafeInput | Prisma.OpeningHourCreateOrConnectWithoutCafeInput[]
  upsert?: Prisma.OpeningHourUpsertWithWhereUniqueWithoutCafeInput | Prisma.OpeningHourUpsertWithWhereUniqueWithoutCafeInput[]
  createMany?: Prisma.OpeningHourCreateManyCafeInputEnvelope
  set?: Prisma.OpeningHourWhereUniqueInput | Prisma.OpeningHourWhereUniqueInput[]
  disconnect?: Prisma.OpeningHourWhereUniqueInput | Prisma.OpeningHourWhereUniqueInput[]
  delete?: Prisma.OpeningHourWhereUniqueInput | Prisma.OpeningHourWhereUniqueInput[]
  connect?: Prisma.OpeningHourWhereUniqueInput | Prisma.OpeningHourWhereUniqueInput[]
  update?: Prisma.OpeningHourUpdateWithWhereUniqueWithoutCafeInput | Prisma.OpeningHourUpdateWithWhereUniqueWithoutCafeInput[]
  updateMany?: Prisma.OpeningHourUpdateManyWithWhereWithoutCafeInput | Prisma.OpeningHourUpdateManyWithWhereWithoutCafeInput[]
  deleteMany?: Prisma.OpeningHourScalarWhereInput | Prisma.OpeningHourScalarWhereInput[]
}

export type OpeningHourUncheckedUpdateManyWithoutCafeNestedInput = {
  create?: Prisma.XOR<Prisma.OpeningHourCreateWithoutCafeInput, Prisma.OpeningHourUncheckedCreateWithoutCafeInput> | Prisma.OpeningHourCreateWithoutCafeInput[] | Prisma.OpeningHourUncheckedCreateWithoutCafeInput[]
  connectOrCreate?: Prisma.OpeningHourCreateOrConnectWithoutCafeInput | Prisma.OpeningHourCreateOrConnectWithoutCafeInput[]
  upsert?: Prisma.OpeningHourUpsertWithWhereUniqueWithoutCafeInput | Prisma.OpeningHourUpsertWithWhereUniqueWithoutCafeInput[]
  createMany?: Prisma.OpeningHourCreateManyCafeInputEnvelope
  set?: Prisma.OpeningHourWhereUniqueInput | Prisma.OpeningHourWhereUniqueInput[]
  disconnect?: Prisma.OpeningHourWhereUniqueInput | Prisma.OpeningHourWhereUniqueInput[]
  delete?: Prisma.OpeningHourWhereUniqueInput | Prisma.OpeningHourWhereUniqueInput[]
  connect?: Prisma.OpeningHourWhereUniqueInput | Prisma.OpeningHourWhereUniqueInput[]
  update?: Prisma.OpeningHourUpdateWithWhereUniqueWithoutCafeInput | Prisma.OpeningHourUpdateWithWhereUniqueWithoutCafeInput[]
  updateMany?: Prisma.OpeningHourUpdateManyWithWhereWithoutCafeInput | Prisma.OpeningHourUpdateManyWithWhereWithoutCafeInput[]
  deleteMany?: Prisma.OpeningHourScalarWhereInput | Prisma.OpeningHourScalarWhereInput[]
}

export type OpeningHourCreateWithoutCafeInput = {
  id?: bigint | number
  dayOfWeek: string
  openTime: Date | string
  closeTime: Date | string
  isClosed?: boolean
}

export type OpeningHourUncheckedCreateWithoutCafeInput = {
  id?: bigint | number
  dayOfWeek: string
  openTime: Date | string
  closeTime: Date | string
  isClosed?: boolean
}

export type OpeningHourCreateOrConnectWithoutCafeInput = {
  where: Prisma.OpeningHourWhereUniqueInput
  create: Prisma.XOR<Prisma.OpeningHourCreateWithoutCafeInput, Prisma.OpeningHourUncheckedCreateWithoutCafeInput>
}

export type OpeningHourCreateManyCafeInputEnvelope = {
  data: Prisma.OpeningHourCreateManyCafeInput | Prisma.OpeningHourCreateManyCafeInput[]
  skipDuplicates?: boolean
}

export type OpeningHourUpsertWithWhereUniqueWithoutCafeInput = {
  where: Prisma.OpeningHourWhereUniqueInput
  update: Prisma.XOR<Prisma.OpeningHourUpdateWithoutCafeInput, Prisma.OpeningHourUncheckedUpdateWithoutCafeInput>
  create: Prisma.XOR<Prisma.OpeningHourCreateWithoutCafeInput, Prisma.OpeningHourUncheckedCreateWithoutCafeInput>
}

export type OpeningHourUpdateWithWhereUniqueWithoutCafeInput = {
  where: Prisma.OpeningHourWhereUniqueInput
  data: Prisma.XOR<Prisma.OpeningHourUpdateWithoutCafeInput, Prisma.OpeningHourUncheckedUpdateWithoutCafeInput>
}

export type OpeningHourUpdateManyWithWhereWithoutCafeInput = {
  where: Prisma.OpeningHourScalarWhereInput
  data: Prisma.XOR<Prisma.OpeningHourUpdateManyMutationInput, Prisma.OpeningHourUncheckedUpdateManyWithoutCafeInput>
}

export type OpeningHourScalarWhereInput = {
  AND?: Prisma.OpeningHourScalarWhereInput | Prisma.OpeningHourScalarWhereInput[]
  OR?: Prisma.OpeningHourScalarWhereInput[]
  NOT?: Prisma.OpeningHourScalarWhereInput | Prisma.OpeningHourScalarWhereInput[]
  id?: Prisma.BigIntFilter<"OpeningHour"> | bigint | number
  cafeId?: Prisma.BigIntFilter<"OpeningHour"> | bigint | number
  dayOfWeek?: Prisma.StringFilter<"OpeningHour"> | string
  openTime?: Prisma.DateTimeFilter<"OpeningHour"> | Date | string
  closeTime?: Prisma.DateTimeFilter<"OpeningHour"> | Date | string
  isClosed?: Prisma.BoolFilter<"OpeningHour"> | boolean
}

export type OpeningHourCreateManyCafeInput = {
  id?: bigint | number
  dayOfWeek: string
  openTime: Date | string
  closeTime: Date | string
  isClosed?: boolean
}

export type OpeningHourUpdateWithoutCafeInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  dayOfWeek?: Prisma.StringFieldUpdateOperationsInput | string
  openTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closeTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isClosed?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type OpeningHourUncheckedUpdateWithoutCafeInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  dayOfWeek?: Prisma.StringFieldUpdateOperationsInput | string
  openTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closeTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isClosed?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type OpeningHourUncheckedUpdateManyWithoutCafeInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  dayOfWeek?: Prisma.StringFieldUpdateOperationsInput | string
  openTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  closeTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isClosed?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type OpeningHourSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cafeId?: boolean
  dayOfWeek?: boolean
  openTime?: boolean
  closeTime?: boolean
  isClosed?: boolean
  cafe?: boolean | Prisma.CafeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["openingHour"]>



export type OpeningHourSelectScalar = {
  id?: boolean
  cafeId?: boolean
  dayOfWeek?: boolean
  openTime?: boolean
  closeTime?: boolean
  isClosed?: boolean
}

export type OpeningHourOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "cafeId" | "dayOfWeek" | "openTime" | "closeTime" | "isClosed", ExtArgs["result"]["openingHour"]>
export type OpeningHourInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cafe?: boolean | Prisma.CafeDefaultArgs<ExtArgs>
}

export type $OpeningHourPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OpeningHour"
  objects: {
    cafe: Prisma.$CafePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    cafeId: bigint
    dayOfWeek: string
    openTime: Date
    closeTime: Date
    isClosed: boolean
  }, ExtArgs["result"]["openingHour"]>
  composites: {}
}

export type OpeningHourGetPayload<S extends boolean | null | undefined | OpeningHourDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OpeningHourPayload, S>

export type OpeningHourCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OpeningHourFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OpeningHourCountAggregateInputType | true
  }

export interface OpeningHourDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OpeningHour'], meta: { name: 'OpeningHour' } }
  /**
   * Find zero or one OpeningHour that matches the filter.
   * @param {OpeningHourFindUniqueArgs} args - Arguments to find a OpeningHour
   * @example
   * // Get one OpeningHour
   * const openingHour = await prisma.openingHour.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OpeningHourFindUniqueArgs>(args: Prisma.SelectSubset<T, OpeningHourFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OpeningHourClient<runtime.Types.Result.GetResult<Prisma.$OpeningHourPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OpeningHour that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OpeningHourFindUniqueOrThrowArgs} args - Arguments to find a OpeningHour
   * @example
   * // Get one OpeningHour
   * const openingHour = await prisma.openingHour.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OpeningHourFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OpeningHourFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OpeningHourClient<runtime.Types.Result.GetResult<Prisma.$OpeningHourPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OpeningHour that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OpeningHourFindFirstArgs} args - Arguments to find a OpeningHour
   * @example
   * // Get one OpeningHour
   * const openingHour = await prisma.openingHour.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OpeningHourFindFirstArgs>(args?: Prisma.SelectSubset<T, OpeningHourFindFirstArgs<ExtArgs>>): Prisma.Prisma__OpeningHourClient<runtime.Types.Result.GetResult<Prisma.$OpeningHourPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OpeningHour that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OpeningHourFindFirstOrThrowArgs} args - Arguments to find a OpeningHour
   * @example
   * // Get one OpeningHour
   * const openingHour = await prisma.openingHour.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OpeningHourFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OpeningHourFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OpeningHourClient<runtime.Types.Result.GetResult<Prisma.$OpeningHourPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OpeningHours that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OpeningHourFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OpeningHours
   * const openingHours = await prisma.openingHour.findMany()
   * 
   * // Get first 10 OpeningHours
   * const openingHours = await prisma.openingHour.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const openingHourWithIdOnly = await prisma.openingHour.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OpeningHourFindManyArgs>(args?: Prisma.SelectSubset<T, OpeningHourFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OpeningHourPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OpeningHour.
   * @param {OpeningHourCreateArgs} args - Arguments to create a OpeningHour.
   * @example
   * // Create one OpeningHour
   * const OpeningHour = await prisma.openingHour.create({
   *   data: {
   *     // ... data to create a OpeningHour
   *   }
   * })
   * 
   */
  create<T extends OpeningHourCreateArgs>(args: Prisma.SelectSubset<T, OpeningHourCreateArgs<ExtArgs>>): Prisma.Prisma__OpeningHourClient<runtime.Types.Result.GetResult<Prisma.$OpeningHourPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OpeningHours.
   * @param {OpeningHourCreateManyArgs} args - Arguments to create many OpeningHours.
   * @example
   * // Create many OpeningHours
   * const openingHour = await prisma.openingHour.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OpeningHourCreateManyArgs>(args?: Prisma.SelectSubset<T, OpeningHourCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a OpeningHour.
   * @param {OpeningHourDeleteArgs} args - Arguments to delete one OpeningHour.
   * @example
   * // Delete one OpeningHour
   * const OpeningHour = await prisma.openingHour.delete({
   *   where: {
   *     // ... filter to delete one OpeningHour
   *   }
   * })
   * 
   */
  delete<T extends OpeningHourDeleteArgs>(args: Prisma.SelectSubset<T, OpeningHourDeleteArgs<ExtArgs>>): Prisma.Prisma__OpeningHourClient<runtime.Types.Result.GetResult<Prisma.$OpeningHourPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OpeningHour.
   * @param {OpeningHourUpdateArgs} args - Arguments to update one OpeningHour.
   * @example
   * // Update one OpeningHour
   * const openingHour = await prisma.openingHour.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OpeningHourUpdateArgs>(args: Prisma.SelectSubset<T, OpeningHourUpdateArgs<ExtArgs>>): Prisma.Prisma__OpeningHourClient<runtime.Types.Result.GetResult<Prisma.$OpeningHourPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OpeningHours.
   * @param {OpeningHourDeleteManyArgs} args - Arguments to filter OpeningHours to delete.
   * @example
   * // Delete a few OpeningHours
   * const { count } = await prisma.openingHour.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OpeningHourDeleteManyArgs>(args?: Prisma.SelectSubset<T, OpeningHourDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OpeningHours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OpeningHourUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OpeningHours
   * const openingHour = await prisma.openingHour.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OpeningHourUpdateManyArgs>(args: Prisma.SelectSubset<T, OpeningHourUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one OpeningHour.
   * @param {OpeningHourUpsertArgs} args - Arguments to update or create a OpeningHour.
   * @example
   * // Update or create a OpeningHour
   * const openingHour = await prisma.openingHour.upsert({
   *   create: {
   *     // ... data to create a OpeningHour
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OpeningHour we want to update
   *   }
   * })
   */
  upsert<T extends OpeningHourUpsertArgs>(args: Prisma.SelectSubset<T, OpeningHourUpsertArgs<ExtArgs>>): Prisma.Prisma__OpeningHourClient<runtime.Types.Result.GetResult<Prisma.$OpeningHourPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OpeningHours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OpeningHourCountArgs} args - Arguments to filter OpeningHours to count.
   * @example
   * // Count the number of OpeningHours
   * const count = await prisma.openingHour.count({
   *   where: {
   *     // ... the filter for the OpeningHours we want to count
   *   }
   * })
  **/
  count<T extends OpeningHourCountArgs>(
    args?: Prisma.Subset<T, OpeningHourCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OpeningHourCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OpeningHour.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OpeningHourAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OpeningHourAggregateArgs>(args: Prisma.Subset<T, OpeningHourAggregateArgs>): Prisma.PrismaPromise<GetOpeningHourAggregateType<T>>

  /**
   * Group by OpeningHour.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OpeningHourGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OpeningHourGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OpeningHourGroupByArgs['orderBy'] }
      : { orderBy?: OpeningHourGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OpeningHourGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOpeningHourGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OpeningHour model
 */
readonly fields: OpeningHourFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OpeningHour.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OpeningHourClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  cafe<T extends Prisma.CafeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CafeDefaultArgs<ExtArgs>>): Prisma.Prisma__CafeClient<runtime.Types.Result.GetResult<Prisma.$CafePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OpeningHour model
 */
export interface OpeningHourFieldRefs {
  readonly id: Prisma.FieldRef<"OpeningHour", 'BigInt'>
  readonly cafeId: Prisma.FieldRef<"OpeningHour", 'BigInt'>
  readonly dayOfWeek: Prisma.FieldRef<"OpeningHour", 'String'>
  readonly openTime: Prisma.FieldRef<"OpeningHour", 'DateTime'>
  readonly closeTime: Prisma.FieldRef<"OpeningHour", 'DateTime'>
  readonly isClosed: Prisma.FieldRef<"OpeningHour", 'Boolean'>
}
    

// Custom InputTypes
/**
 * OpeningHour findUnique
 */
export type OpeningHourFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OpeningHour
   */
  select?: Prisma.OpeningHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OpeningHour
   */
  omit?: Prisma.OpeningHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OpeningHourInclude<ExtArgs> | null
  /**
   * Filter, which OpeningHour to fetch.
   */
  where: Prisma.OpeningHourWhereUniqueInput
}

/**
 * OpeningHour findUniqueOrThrow
 */
export type OpeningHourFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OpeningHour
   */
  select?: Prisma.OpeningHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OpeningHour
   */
  omit?: Prisma.OpeningHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OpeningHourInclude<ExtArgs> | null
  /**
   * Filter, which OpeningHour to fetch.
   */
  where: Prisma.OpeningHourWhereUniqueInput
}

/**
 * OpeningHour findFirst
 */
export type OpeningHourFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OpeningHour
   */
  select?: Prisma.OpeningHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OpeningHour
   */
  omit?: Prisma.OpeningHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OpeningHourInclude<ExtArgs> | null
  /**
   * Filter, which OpeningHour to fetch.
   */
  where?: Prisma.OpeningHourWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OpeningHours to fetch.
   */
  orderBy?: Prisma.OpeningHourOrderByWithRelationInput | Prisma.OpeningHourOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OpeningHours.
   */
  cursor?: Prisma.OpeningHourWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OpeningHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OpeningHours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OpeningHours.
   */
  distinct?: Prisma.OpeningHourScalarFieldEnum | Prisma.OpeningHourScalarFieldEnum[]
}

/**
 * OpeningHour findFirstOrThrow
 */
export type OpeningHourFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OpeningHour
   */
  select?: Prisma.OpeningHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OpeningHour
   */
  omit?: Prisma.OpeningHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OpeningHourInclude<ExtArgs> | null
  /**
   * Filter, which OpeningHour to fetch.
   */
  where?: Prisma.OpeningHourWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OpeningHours to fetch.
   */
  orderBy?: Prisma.OpeningHourOrderByWithRelationInput | Prisma.OpeningHourOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OpeningHours.
   */
  cursor?: Prisma.OpeningHourWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OpeningHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OpeningHours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OpeningHours.
   */
  distinct?: Prisma.OpeningHourScalarFieldEnum | Prisma.OpeningHourScalarFieldEnum[]
}

/**
 * OpeningHour findMany
 */
export type OpeningHourFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OpeningHour
   */
  select?: Prisma.OpeningHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OpeningHour
   */
  omit?: Prisma.OpeningHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OpeningHourInclude<ExtArgs> | null
  /**
   * Filter, which OpeningHours to fetch.
   */
  where?: Prisma.OpeningHourWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OpeningHours to fetch.
   */
  orderBy?: Prisma.OpeningHourOrderByWithRelationInput | Prisma.OpeningHourOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OpeningHours.
   */
  cursor?: Prisma.OpeningHourWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OpeningHours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OpeningHours.
   */
  skip?: number
  distinct?: Prisma.OpeningHourScalarFieldEnum | Prisma.OpeningHourScalarFieldEnum[]
}

/**
 * OpeningHour create
 */
export type OpeningHourCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OpeningHour
   */
  select?: Prisma.OpeningHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OpeningHour
   */
  omit?: Prisma.OpeningHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OpeningHourInclude<ExtArgs> | null
  /**
   * The data needed to create a OpeningHour.
   */
  data: Prisma.XOR<Prisma.OpeningHourCreateInput, Prisma.OpeningHourUncheckedCreateInput>
}

/**
 * OpeningHour createMany
 */
export type OpeningHourCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OpeningHours.
   */
  data: Prisma.OpeningHourCreateManyInput | Prisma.OpeningHourCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OpeningHour update
 */
export type OpeningHourUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OpeningHour
   */
  select?: Prisma.OpeningHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OpeningHour
   */
  omit?: Prisma.OpeningHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OpeningHourInclude<ExtArgs> | null
  /**
   * The data needed to update a OpeningHour.
   */
  data: Prisma.XOR<Prisma.OpeningHourUpdateInput, Prisma.OpeningHourUncheckedUpdateInput>
  /**
   * Choose, which OpeningHour to update.
   */
  where: Prisma.OpeningHourWhereUniqueInput
}

/**
 * OpeningHour updateMany
 */
export type OpeningHourUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OpeningHours.
   */
  data: Prisma.XOR<Prisma.OpeningHourUpdateManyMutationInput, Prisma.OpeningHourUncheckedUpdateManyInput>
  /**
   * Filter which OpeningHours to update
   */
  where?: Prisma.OpeningHourWhereInput
  /**
   * Limit how many OpeningHours to update.
   */
  limit?: number
}

/**
 * OpeningHour upsert
 */
export type OpeningHourUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OpeningHour
   */
  select?: Prisma.OpeningHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OpeningHour
   */
  omit?: Prisma.OpeningHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OpeningHourInclude<ExtArgs> | null
  /**
   * The filter to search for the OpeningHour to update in case it exists.
   */
  where: Prisma.OpeningHourWhereUniqueInput
  /**
   * In case the OpeningHour found by the `where` argument doesn't exist, create a new OpeningHour with this data.
   */
  create: Prisma.XOR<Prisma.OpeningHourCreateInput, Prisma.OpeningHourUncheckedCreateInput>
  /**
   * In case the OpeningHour was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OpeningHourUpdateInput, Prisma.OpeningHourUncheckedUpdateInput>
}

/**
 * OpeningHour delete
 */
export type OpeningHourDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OpeningHour
   */
  select?: Prisma.OpeningHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OpeningHour
   */
  omit?: Prisma.OpeningHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OpeningHourInclude<ExtArgs> | null
  /**
   * Filter which OpeningHour to delete.
   */
  where: Prisma.OpeningHourWhereUniqueInput
}

/**
 * OpeningHour deleteMany
 */
export type OpeningHourDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OpeningHours to delete
   */
  where?: Prisma.OpeningHourWhereInput
  /**
   * Limit how many OpeningHours to delete.
   */
  limit?: number
}

/**
 * OpeningHour without action
 */
export type OpeningHourDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OpeningHour
   */
  select?: Prisma.OpeningHourSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OpeningHour
   */
  omit?: Prisma.OpeningHourOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OpeningHourInclude<ExtArgs> | null
}
