
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PaymentMethod` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PaymentMethod
 * 
 */
export type PaymentMethodModel = runtime.Types.Result.DefaultSelection<Prisma.$PaymentMethodPayload>

export type AggregatePaymentMethod = {
  _count: PaymentMethodCountAggregateOutputType | null
  _avg: PaymentMethodAvgAggregateOutputType | null
  _sum: PaymentMethodSumAggregateOutputType | null
  _min: PaymentMethodMinAggregateOutputType | null
  _max: PaymentMethodMaxAggregateOutputType | null
}

export type PaymentMethodAvgAggregateOutputType = {
  id: number | null
}

export type PaymentMethodSumAggregateOutputType = {
  id: bigint | null
}

export type PaymentMethodMinAggregateOutputType = {
  id: bigint | null
  code: string | null
  label: string | null
}

export type PaymentMethodMaxAggregateOutputType = {
  id: bigint | null
  code: string | null
  label: string | null
}

export type PaymentMethodCountAggregateOutputType = {
  id: number
  code: number
  label: number
  _all: number
}


export type PaymentMethodAvgAggregateInputType = {
  id?: true
}

export type PaymentMethodSumAggregateInputType = {
  id?: true
}

export type PaymentMethodMinAggregateInputType = {
  id?: true
  code?: true
  label?: true
}

export type PaymentMethodMaxAggregateInputType = {
  id?: true
  code?: true
  label?: true
}

export type PaymentMethodCountAggregateInputType = {
  id?: true
  code?: true
  label?: true
  _all?: true
}

export type PaymentMethodAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PaymentMethod to aggregate.
   */
  where?: Prisma.PaymentMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaymentMethods to fetch.
   */
  orderBy?: Prisma.PaymentMethodOrderByWithRelationInput | Prisma.PaymentMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PaymentMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaymentMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaymentMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PaymentMethods
  **/
  _count?: true | PaymentMethodCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PaymentMethodAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PaymentMethodSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PaymentMethodMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PaymentMethodMaxAggregateInputType
}

export type GetPaymentMethodAggregateType<T extends PaymentMethodAggregateArgs> = {
      [P in keyof T & keyof AggregatePaymentMethod]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePaymentMethod[P]>
    : Prisma.GetScalarType<T[P], AggregatePaymentMethod[P]>
}




export type PaymentMethodGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PaymentMethodWhereInput
  orderBy?: Prisma.PaymentMethodOrderByWithAggregationInput | Prisma.PaymentMethodOrderByWithAggregationInput[]
  by: Prisma.PaymentMethodScalarFieldEnum[] | Prisma.PaymentMethodScalarFieldEnum
  having?: Prisma.PaymentMethodScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PaymentMethodCountAggregateInputType | true
  _avg?: PaymentMethodAvgAggregateInputType
  _sum?: PaymentMethodSumAggregateInputType
  _min?: PaymentMethodMinAggregateInputType
  _max?: PaymentMethodMaxAggregateInputType
}

export type PaymentMethodGroupByOutputType = {
  id: bigint
  code: string
  label: string
  _count: PaymentMethodCountAggregateOutputType | null
  _avg: PaymentMethodAvgAggregateOutputType | null
  _sum: PaymentMethodSumAggregateOutputType | null
  _min: PaymentMethodMinAggregateOutputType | null
  _max: PaymentMethodMaxAggregateOutputType | null
}

type GetPaymentMethodGroupByPayload<T extends PaymentMethodGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PaymentMethodGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PaymentMethodGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PaymentMethodGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PaymentMethodGroupByOutputType[P]>
      }
    >
  >



export type PaymentMethodWhereInput = {
  AND?: Prisma.PaymentMethodWhereInput | Prisma.PaymentMethodWhereInput[]
  OR?: Prisma.PaymentMethodWhereInput[]
  NOT?: Prisma.PaymentMethodWhereInput | Prisma.PaymentMethodWhereInput[]
  id?: Prisma.BigIntFilter<"PaymentMethod"> | bigint | number
  code?: Prisma.StringFilter<"PaymentMethod"> | string
  label?: Prisma.StringFilter<"PaymentMethod"> | string
  cafes?: Prisma.CafePaymentMethodListRelationFilter
}

export type PaymentMethodOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  label?: Prisma.SortOrder
  cafes?: Prisma.CafePaymentMethodOrderByRelationAggregateInput
  _relevance?: Prisma.PaymentMethodOrderByRelevanceInput
}

export type PaymentMethodWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  code?: string
  AND?: Prisma.PaymentMethodWhereInput | Prisma.PaymentMethodWhereInput[]
  OR?: Prisma.PaymentMethodWhereInput[]
  NOT?: Prisma.PaymentMethodWhereInput | Prisma.PaymentMethodWhereInput[]
  label?: Prisma.StringFilter<"PaymentMethod"> | string
  cafes?: Prisma.CafePaymentMethodListRelationFilter
}, "id" | "code">

export type PaymentMethodOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  label?: Prisma.SortOrder
  _count?: Prisma.PaymentMethodCountOrderByAggregateInput
  _avg?: Prisma.PaymentMethodAvgOrderByAggregateInput
  _max?: Prisma.PaymentMethodMaxOrderByAggregateInput
  _min?: Prisma.PaymentMethodMinOrderByAggregateInput
  _sum?: Prisma.PaymentMethodSumOrderByAggregateInput
}

export type PaymentMethodScalarWhereWithAggregatesInput = {
  AND?: Prisma.PaymentMethodScalarWhereWithAggregatesInput | Prisma.PaymentMethodScalarWhereWithAggregatesInput[]
  OR?: Prisma.PaymentMethodScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PaymentMethodScalarWhereWithAggregatesInput | Prisma.PaymentMethodScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"PaymentMethod"> | bigint | number
  code?: Prisma.StringWithAggregatesFilter<"PaymentMethod"> | string
  label?: Prisma.StringWithAggregatesFilter<"PaymentMethod"> | string
}

export type PaymentMethodCreateInput = {
  id?: bigint | number
  code: string
  label: string
  cafes?: Prisma.CafePaymentMethodCreateNestedManyWithoutPaymentMethodInput
}

export type PaymentMethodUncheckedCreateInput = {
  id?: bigint | number
  code: string
  label: string
  cafes?: Prisma.CafePaymentMethodUncheckedCreateNestedManyWithoutPaymentMethodInput
}

export type PaymentMethodUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  cafes?: Prisma.CafePaymentMethodUpdateManyWithoutPaymentMethodNestedInput
}

export type PaymentMethodUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  cafes?: Prisma.CafePaymentMethodUncheckedUpdateManyWithoutPaymentMethodNestedInput
}

export type PaymentMethodCreateManyInput = {
  id?: bigint | number
  code: string
  label: string
}

export type PaymentMethodUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PaymentMethodUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PaymentMethodOrderByRelevanceInput = {
  fields: Prisma.PaymentMethodOrderByRelevanceFieldEnum | Prisma.PaymentMethodOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type PaymentMethodCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  label?: Prisma.SortOrder
}

export type PaymentMethodAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type PaymentMethodMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  label?: Prisma.SortOrder
}

export type PaymentMethodMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  label?: Prisma.SortOrder
}

export type PaymentMethodSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type PaymentMethodScalarRelationFilter = {
  is?: Prisma.PaymentMethodWhereInput
  isNot?: Prisma.PaymentMethodWhereInput
}

export type PaymentMethodCreateNestedOneWithoutCafesInput = {
  create?: Prisma.XOR<Prisma.PaymentMethodCreateWithoutCafesInput, Prisma.PaymentMethodUncheckedCreateWithoutCafesInput>
  connectOrCreate?: Prisma.PaymentMethodCreateOrConnectWithoutCafesInput
  connect?: Prisma.PaymentMethodWhereUniqueInput
}

export type PaymentMethodUpdateOneRequiredWithoutCafesNestedInput = {
  create?: Prisma.XOR<Prisma.PaymentMethodCreateWithoutCafesInput, Prisma.PaymentMethodUncheckedCreateWithoutCafesInput>
  connectOrCreate?: Prisma.PaymentMethodCreateOrConnectWithoutCafesInput
  upsert?: Prisma.PaymentMethodUpsertWithoutCafesInput
  connect?: Prisma.PaymentMethodWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PaymentMethodUpdateToOneWithWhereWithoutCafesInput, Prisma.PaymentMethodUpdateWithoutCafesInput>, Prisma.PaymentMethodUncheckedUpdateWithoutCafesInput>
}

export type PaymentMethodCreateWithoutCafesInput = {
  id?: bigint | number
  code: string
  label: string
}

export type PaymentMethodUncheckedCreateWithoutCafesInput = {
  id?: bigint | number
  code: string
  label: string
}

export type PaymentMethodCreateOrConnectWithoutCafesInput = {
  where: Prisma.PaymentMethodWhereUniqueInput
  create: Prisma.XOR<Prisma.PaymentMethodCreateWithoutCafesInput, Prisma.PaymentMethodUncheckedCreateWithoutCafesInput>
}

export type PaymentMethodUpsertWithoutCafesInput = {
  update: Prisma.XOR<Prisma.PaymentMethodUpdateWithoutCafesInput, Prisma.PaymentMethodUncheckedUpdateWithoutCafesInput>
  create: Prisma.XOR<Prisma.PaymentMethodCreateWithoutCafesInput, Prisma.PaymentMethodUncheckedCreateWithoutCafesInput>
  where?: Prisma.PaymentMethodWhereInput
}

export type PaymentMethodUpdateToOneWithWhereWithoutCafesInput = {
  where?: Prisma.PaymentMethodWhereInput
  data: Prisma.XOR<Prisma.PaymentMethodUpdateWithoutCafesInput, Prisma.PaymentMethodUncheckedUpdateWithoutCafesInput>
}

export type PaymentMethodUpdateWithoutCafesInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PaymentMethodUncheckedUpdateWithoutCafesInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type PaymentMethodCountOutputType
 */

export type PaymentMethodCountOutputType = {
  cafes: number
}

export type PaymentMethodCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cafes?: boolean | PaymentMethodCountOutputTypeCountCafesArgs
}

/**
 * PaymentMethodCountOutputType without action
 */
export type PaymentMethodCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentMethodCountOutputType
   */
  select?: Prisma.PaymentMethodCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PaymentMethodCountOutputType without action
 */
export type PaymentMethodCountOutputTypeCountCafesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CafePaymentMethodWhereInput
}


export type PaymentMethodSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  label?: boolean
  cafes?: boolean | Prisma.PaymentMethod$cafesArgs<ExtArgs>
  _count?: boolean | Prisma.PaymentMethodCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paymentMethod"]>



export type PaymentMethodSelectScalar = {
  id?: boolean
  code?: boolean
  label?: boolean
}

export type PaymentMethodOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "code" | "label", ExtArgs["result"]["paymentMethod"]>
export type PaymentMethodInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cafes?: boolean | Prisma.PaymentMethod$cafesArgs<ExtArgs>
  _count?: boolean | Prisma.PaymentMethodCountOutputTypeDefaultArgs<ExtArgs>
}

export type $PaymentMethodPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PaymentMethod"
  objects: {
    cafes: Prisma.$CafePaymentMethodPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    code: string
    label: string
  }, ExtArgs["result"]["paymentMethod"]>
  composites: {}
}

export type PaymentMethodGetPayload<S extends boolean | null | undefined | PaymentMethodDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PaymentMethodPayload, S>

export type PaymentMethodCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PaymentMethodFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PaymentMethodCountAggregateInputType | true
  }

export interface PaymentMethodDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PaymentMethod'], meta: { name: 'PaymentMethod' } }
  /**
   * Find zero or one PaymentMethod that matches the filter.
   * @param {PaymentMethodFindUniqueArgs} args - Arguments to find a PaymentMethod
   * @example
   * // Get one PaymentMethod
   * const paymentMethod = await prisma.paymentMethod.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PaymentMethodFindUniqueArgs>(args: Prisma.SelectSubset<T, PaymentMethodFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$PaymentMethodPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PaymentMethod that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PaymentMethodFindUniqueOrThrowArgs} args - Arguments to find a PaymentMethod
   * @example
   * // Get one PaymentMethod
   * const paymentMethod = await prisma.paymentMethod.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PaymentMethodFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PaymentMethodFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$PaymentMethodPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PaymentMethod that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentMethodFindFirstArgs} args - Arguments to find a PaymentMethod
   * @example
   * // Get one PaymentMethod
   * const paymentMethod = await prisma.paymentMethod.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PaymentMethodFindFirstArgs>(args?: Prisma.SelectSubset<T, PaymentMethodFindFirstArgs<ExtArgs>>): Prisma.Prisma__PaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$PaymentMethodPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PaymentMethod that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentMethodFindFirstOrThrowArgs} args - Arguments to find a PaymentMethod
   * @example
   * // Get one PaymentMethod
   * const paymentMethod = await prisma.paymentMethod.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PaymentMethodFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PaymentMethodFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$PaymentMethodPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PaymentMethods that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentMethodFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PaymentMethods
   * const paymentMethods = await prisma.paymentMethod.findMany()
   * 
   * // Get first 10 PaymentMethods
   * const paymentMethods = await prisma.paymentMethod.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const paymentMethodWithIdOnly = await prisma.paymentMethod.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PaymentMethodFindManyArgs>(args?: Prisma.SelectSubset<T, PaymentMethodFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaymentMethodPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PaymentMethod.
   * @param {PaymentMethodCreateArgs} args - Arguments to create a PaymentMethod.
   * @example
   * // Create one PaymentMethod
   * const PaymentMethod = await prisma.paymentMethod.create({
   *   data: {
   *     // ... data to create a PaymentMethod
   *   }
   * })
   * 
   */
  create<T extends PaymentMethodCreateArgs>(args: Prisma.SelectSubset<T, PaymentMethodCreateArgs<ExtArgs>>): Prisma.Prisma__PaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$PaymentMethodPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PaymentMethods.
   * @param {PaymentMethodCreateManyArgs} args - Arguments to create many PaymentMethods.
   * @example
   * // Create many PaymentMethods
   * const paymentMethod = await prisma.paymentMethod.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PaymentMethodCreateManyArgs>(args?: Prisma.SelectSubset<T, PaymentMethodCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a PaymentMethod.
   * @param {PaymentMethodDeleteArgs} args - Arguments to delete one PaymentMethod.
   * @example
   * // Delete one PaymentMethod
   * const PaymentMethod = await prisma.paymentMethod.delete({
   *   where: {
   *     // ... filter to delete one PaymentMethod
   *   }
   * })
   * 
   */
  delete<T extends PaymentMethodDeleteArgs>(args: Prisma.SelectSubset<T, PaymentMethodDeleteArgs<ExtArgs>>): Prisma.Prisma__PaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$PaymentMethodPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PaymentMethod.
   * @param {PaymentMethodUpdateArgs} args - Arguments to update one PaymentMethod.
   * @example
   * // Update one PaymentMethod
   * const paymentMethod = await prisma.paymentMethod.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PaymentMethodUpdateArgs>(args: Prisma.SelectSubset<T, PaymentMethodUpdateArgs<ExtArgs>>): Prisma.Prisma__PaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$PaymentMethodPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PaymentMethods.
   * @param {PaymentMethodDeleteManyArgs} args - Arguments to filter PaymentMethods to delete.
   * @example
   * // Delete a few PaymentMethods
   * const { count } = await prisma.paymentMethod.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PaymentMethodDeleteManyArgs>(args?: Prisma.SelectSubset<T, PaymentMethodDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PaymentMethods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentMethodUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PaymentMethods
   * const paymentMethod = await prisma.paymentMethod.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PaymentMethodUpdateManyArgs>(args: Prisma.SelectSubset<T, PaymentMethodUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one PaymentMethod.
   * @param {PaymentMethodUpsertArgs} args - Arguments to update or create a PaymentMethod.
   * @example
   * // Update or create a PaymentMethod
   * const paymentMethod = await prisma.paymentMethod.upsert({
   *   create: {
   *     // ... data to create a PaymentMethod
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PaymentMethod we want to update
   *   }
   * })
   */
  upsert<T extends PaymentMethodUpsertArgs>(args: Prisma.SelectSubset<T, PaymentMethodUpsertArgs<ExtArgs>>): Prisma.Prisma__PaymentMethodClient<runtime.Types.Result.GetResult<Prisma.$PaymentMethodPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PaymentMethods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentMethodCountArgs} args - Arguments to filter PaymentMethods to count.
   * @example
   * // Count the number of PaymentMethods
   * const count = await prisma.paymentMethod.count({
   *   where: {
   *     // ... the filter for the PaymentMethods we want to count
   *   }
   * })
  **/
  count<T extends PaymentMethodCountArgs>(
    args?: Prisma.Subset<T, PaymentMethodCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PaymentMethodCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PaymentMethod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentMethodAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PaymentMethodAggregateArgs>(args: Prisma.Subset<T, PaymentMethodAggregateArgs>): Prisma.PrismaPromise<GetPaymentMethodAggregateType<T>>

  /**
   * Group by PaymentMethod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentMethodGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PaymentMethodGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PaymentMethodGroupByArgs['orderBy'] }
      : { orderBy?: PaymentMethodGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PaymentMethodGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPaymentMethodGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PaymentMethod model
 */
readonly fields: PaymentMethodFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PaymentMethod.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PaymentMethodClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  cafes<T extends Prisma.PaymentMethod$cafesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PaymentMethod$cafesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CafePaymentMethodPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PaymentMethod model
 */
export interface PaymentMethodFieldRefs {
  readonly id: Prisma.FieldRef<"PaymentMethod", 'BigInt'>
  readonly code: Prisma.FieldRef<"PaymentMethod", 'String'>
  readonly label: Prisma.FieldRef<"PaymentMethod", 'String'>
}
    

// Custom InputTypes
/**
 * PaymentMethod findUnique
 */
export type PaymentMethodFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentMethod
   */
  select?: Prisma.PaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentMethod
   */
  omit?: Prisma.PaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentMethodInclude<ExtArgs> | null
  /**
   * Filter, which PaymentMethod to fetch.
   */
  where: Prisma.PaymentMethodWhereUniqueInput
}

/**
 * PaymentMethod findUniqueOrThrow
 */
export type PaymentMethodFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentMethod
   */
  select?: Prisma.PaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentMethod
   */
  omit?: Prisma.PaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentMethodInclude<ExtArgs> | null
  /**
   * Filter, which PaymentMethod to fetch.
   */
  where: Prisma.PaymentMethodWhereUniqueInput
}

/**
 * PaymentMethod findFirst
 */
export type PaymentMethodFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentMethod
   */
  select?: Prisma.PaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentMethod
   */
  omit?: Prisma.PaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentMethodInclude<ExtArgs> | null
  /**
   * Filter, which PaymentMethod to fetch.
   */
  where?: Prisma.PaymentMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaymentMethods to fetch.
   */
  orderBy?: Prisma.PaymentMethodOrderByWithRelationInput | Prisma.PaymentMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PaymentMethods.
   */
  cursor?: Prisma.PaymentMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaymentMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaymentMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PaymentMethods.
   */
  distinct?: Prisma.PaymentMethodScalarFieldEnum | Prisma.PaymentMethodScalarFieldEnum[]
}

/**
 * PaymentMethod findFirstOrThrow
 */
export type PaymentMethodFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentMethod
   */
  select?: Prisma.PaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentMethod
   */
  omit?: Prisma.PaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentMethodInclude<ExtArgs> | null
  /**
   * Filter, which PaymentMethod to fetch.
   */
  where?: Prisma.PaymentMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaymentMethods to fetch.
   */
  orderBy?: Prisma.PaymentMethodOrderByWithRelationInput | Prisma.PaymentMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PaymentMethods.
   */
  cursor?: Prisma.PaymentMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaymentMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaymentMethods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PaymentMethods.
   */
  distinct?: Prisma.PaymentMethodScalarFieldEnum | Prisma.PaymentMethodScalarFieldEnum[]
}

/**
 * PaymentMethod findMany
 */
export type PaymentMethodFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentMethod
   */
  select?: Prisma.PaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentMethod
   */
  omit?: Prisma.PaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentMethodInclude<ExtArgs> | null
  /**
   * Filter, which PaymentMethods to fetch.
   */
  where?: Prisma.PaymentMethodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaymentMethods to fetch.
   */
  orderBy?: Prisma.PaymentMethodOrderByWithRelationInput | Prisma.PaymentMethodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PaymentMethods.
   */
  cursor?: Prisma.PaymentMethodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaymentMethods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaymentMethods.
   */
  skip?: number
  distinct?: Prisma.PaymentMethodScalarFieldEnum | Prisma.PaymentMethodScalarFieldEnum[]
}

/**
 * PaymentMethod create
 */
export type PaymentMethodCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentMethod
   */
  select?: Prisma.PaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentMethod
   */
  omit?: Prisma.PaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentMethodInclude<ExtArgs> | null
  /**
   * The data needed to create a PaymentMethod.
   */
  data: Prisma.XOR<Prisma.PaymentMethodCreateInput, Prisma.PaymentMethodUncheckedCreateInput>
}

/**
 * PaymentMethod createMany
 */
export type PaymentMethodCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PaymentMethods.
   */
  data: Prisma.PaymentMethodCreateManyInput | Prisma.PaymentMethodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PaymentMethod update
 */
export type PaymentMethodUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentMethod
   */
  select?: Prisma.PaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentMethod
   */
  omit?: Prisma.PaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentMethodInclude<ExtArgs> | null
  /**
   * The data needed to update a PaymentMethod.
   */
  data: Prisma.XOR<Prisma.PaymentMethodUpdateInput, Prisma.PaymentMethodUncheckedUpdateInput>
  /**
   * Choose, which PaymentMethod to update.
   */
  where: Prisma.PaymentMethodWhereUniqueInput
}

/**
 * PaymentMethod updateMany
 */
export type PaymentMethodUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PaymentMethods.
   */
  data: Prisma.XOR<Prisma.PaymentMethodUpdateManyMutationInput, Prisma.PaymentMethodUncheckedUpdateManyInput>
  /**
   * Filter which PaymentMethods to update
   */
  where?: Prisma.PaymentMethodWhereInput
  /**
   * Limit how many PaymentMethods to update.
   */
  limit?: number
}

/**
 * PaymentMethod upsert
 */
export type PaymentMethodUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentMethod
   */
  select?: Prisma.PaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentMethod
   */
  omit?: Prisma.PaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentMethodInclude<ExtArgs> | null
  /**
   * The filter to search for the PaymentMethod to update in case it exists.
   */
  where: Prisma.PaymentMethodWhereUniqueInput
  /**
   * In case the PaymentMethod found by the `where` argument doesn't exist, create a new PaymentMethod with this data.
   */
  create: Prisma.XOR<Prisma.PaymentMethodCreateInput, Prisma.PaymentMethodUncheckedCreateInput>
  /**
   * In case the PaymentMethod was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PaymentMethodUpdateInput, Prisma.PaymentMethodUncheckedUpdateInput>
}

/**
 * PaymentMethod delete
 */
export type PaymentMethodDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentMethod
   */
  select?: Prisma.PaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentMethod
   */
  omit?: Prisma.PaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentMethodInclude<ExtArgs> | null
  /**
   * Filter which PaymentMethod to delete.
   */
  where: Prisma.PaymentMethodWhereUniqueInput
}

/**
 * PaymentMethod deleteMany
 */
export type PaymentMethodDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PaymentMethods to delete
   */
  where?: Prisma.PaymentMethodWhereInput
  /**
   * Limit how many PaymentMethods to delete.
   */
  limit?: number
}

/**
 * PaymentMethod.cafes
 */
export type PaymentMethod$cafesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CafePaymentMethod
   */
  select?: Prisma.CafePaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CafePaymentMethod
   */
  omit?: Prisma.CafePaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CafePaymentMethodInclude<ExtArgs> | null
  where?: Prisma.CafePaymentMethodWhereInput
  orderBy?: Prisma.CafePaymentMethodOrderByWithRelationInput | Prisma.CafePaymentMethodOrderByWithRelationInput[]
  cursor?: Prisma.CafePaymentMethodWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CafePaymentMethodScalarFieldEnum | Prisma.CafePaymentMethodScalarFieldEnum[]
}

/**
 * PaymentMethod without action
 */
export type PaymentMethodDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentMethod
   */
  select?: Prisma.PaymentMethodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentMethod
   */
  omit?: Prisma.PaymentMethodOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentMethodInclude<ExtArgs> | null
}
