
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Cafe: 'Cafe',
  OpeningHour: 'OpeningHour',
  PaymentMethod: 'PaymentMethod',
  CafePaymentMethod: 'CafePaymentMethod'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CafeScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  address: 'address',
  latitude: 'latitude',
  longitude: 'longitude',
  googleMapsUrl: 'googleMapsUrl',
  instagramUrl: 'instagramUrl',
  wifi: 'wifi',
  parking: 'parking',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CafeScalarFieldEnum = (typeof CafeScalarFieldEnum)[keyof typeof CafeScalarFieldEnum]


export const OpeningHourScalarFieldEnum = {
  id: 'id',
  cafeId: 'cafeId',
  dayOfWeek: 'dayOfWeek',
  openTime: 'openTime',
  closeTime: 'closeTime',
  isClosed: 'isClosed'
} as const

export type OpeningHourScalarFieldEnum = (typeof OpeningHourScalarFieldEnum)[keyof typeof OpeningHourScalarFieldEnum]


export const PaymentMethodScalarFieldEnum = {
  id: 'id',
  code: 'code',
  label: 'label'
} as const

export type PaymentMethodScalarFieldEnum = (typeof PaymentMethodScalarFieldEnum)[keyof typeof PaymentMethodScalarFieldEnum]


export const CafePaymentMethodScalarFieldEnum = {
  cafeId: 'cafeId',
  paymentMethodId: 'paymentMethodId'
} as const

export type CafePaymentMethodScalarFieldEnum = (typeof CafePaymentMethodScalarFieldEnum)[keyof typeof CafePaymentMethodScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const CafeOrderByRelevanceFieldEnum = {
  slug: 'slug',
  name: 'name',
  address: 'address',
  googleMapsUrl: 'googleMapsUrl',
  instagramUrl: 'instagramUrl',
  parking: 'parking'
} as const

export type CafeOrderByRelevanceFieldEnum = (typeof CafeOrderByRelevanceFieldEnum)[keyof typeof CafeOrderByRelevanceFieldEnum]


export const OpeningHourOrderByRelevanceFieldEnum = {
  dayOfWeek: 'dayOfWeek'
} as const

export type OpeningHourOrderByRelevanceFieldEnum = (typeof OpeningHourOrderByRelevanceFieldEnum)[keyof typeof OpeningHourOrderByRelevanceFieldEnum]


export const PaymentMethodOrderByRelevanceFieldEnum = {
  code: 'code',
  label: 'label'
} as const

export type PaymentMethodOrderByRelevanceFieldEnum = (typeof PaymentMethodOrderByRelevanceFieldEnum)[keyof typeof PaymentMethodOrderByRelevanceFieldEnum]

